# EpiCoV 2020

- Number of sequences: `200,524`
- Collection dates: 1 Jan 20 to 6 Jul 20

In [1]:
# General
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

# Plotting libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Custom helpers
from utils import (standardize_country_name, get_continent, choropleth_continent,
choropleth_world, map_age_to_group, col_fillna, plot_dominant_choropleth, inclusion_exclusion,
standardize_vaccine_status, map_pat_status)

import warnings
warnings.filterwarnings("ignore")

In [2]:
YEAR = "2020"
DATA_PATH = os.path.expanduser(f"~/gcs-data/Full_data/epicov_{YEAR}_200k.csv")
if not os.path.exists(DATA_PATH):
    DATA_PATH = os.path.expanduser(f"~/gcs-data/Full_data/epicov_{YEAR}_200k.parquet")
PLOTS_PATH = f"Nov25_plots/epicov_{YEAR}/"

os.makedirs(PLOTS_PATH, exist_ok=True)

The patient status is varying too much, let's standardize it using the manual annotaion by Dr. Miae Lee.

In [3]:
# For patient status mapping
df_pat = pd.read_excel(os.path.expanduser(f"~/gcs-data/patient_status_mapping_MLedit.xlsx"))
df_pat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pat_stat             117 non-null    object
 1   clinical status      118 non-null    object
 2   hospitalized status  118 non-null    object
 3   severity             118 non-null    object
 4   category             118 non-null    object
 5   remarks              49 non-null     object
 6   further remarks      35 non-null     object
dtypes: object(7)
memory usage: 6.6+ KB

In [4]:
%%time
df = pd.read_csv(DATA_PATH) if DATA_PATH.endswith(".csv") else pd.read_parquet(DATA_PATH)
df.sort_values(by=["Collection date"], inplace=True)
df.shape, df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200524 entries, 8434 to 200523
Data columns (total 18 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Accession ID                     200524 non-null  object
 1   Submission date                  200524 non-null  object
 2   Virus name                       200524 non-null  object
 3   Collection date                  200524 non-null  object
 4   Location                         200524 non-null  object
 5   Host                             200524 non-null  object
 6   Additional location information  6210 non-null    object
 7   Sampling strategy                11252 non-null   object
 8   Gender                           200524 non-null  object
 9   Patient age                      200519 non-null  object
 10  Patient status                   200509 non-null  object
 11  Last vaccinated                  76 non-null      object
 12  Passage                          200524 non-null  object
 13  Specimen                         66115 non-null   object
 14  Additional host information      2166 non-null    object
 15  Lineage                          200524 non-null  object
 16  Clade                            200521 non-null  object
 17  AA Substitutions                 200524 non-null  object
dtypes: object(18)
memory usage: 29.1+ MB
CPU times: user 932 ms, sys: 78 ms, total: 1.01 s
Wall time: 1.01 s

((200524, 18), None)

In [5]:
df.nunique()

Accession ID                       200524
Submission date                      1016
Virus name                         200478
Collection date                       188
Location                             4418
Host                                    1
Additional location information      1035
Sampling strategy                     111
Gender                                133
Patient age                           311
Patient status                        133
Last vaccinated                        12
Passage                               103
Specimen                              329
Additional host information           417
Lineage                               946
Clade                                  11
AA Substitutions                    70260
dtype: int64

## Clean the data

Let's fill in missing values, fix spurious values and standardize a few column values

### Gender

In [6]:
df["Gender"].value_counts()

Gender
unknown    126740
Male        38933
Female      34391
49.0           17
unknowm        15
            ...
64              1
9               1
13              1
62.0            1
23.0            1
Name: count, Length: 133, dtype: int64

In [7]:
a = "100"
a[0].isdigit()

True

In [8]:
[x for x in df["Patient status"].unique() if str(x)[0].isdigit()], [x for x in df["Gender"].unique() if str(x)[0].isdigit()]

([],
 ['3.0',
  '66.0',
  '57.0',
  '69.0',
  '76.0',
  '38.0',
  '63.0',
  '65',
  '58.0',
  '41.0',
  '37.0',
  '34.0',
  '64.0',
  '49.0',
  '31.0',
  '46.0',
  '17.0',
  '39.0',
  '47.0',
  '74.0',
  '42.0',
  '48.0',
  '35.0',
  '79.0',
  '65.0',
  '60.0',
  '33.0',
  '32.0',
  '24.0',
  '68.0',
  '75.0',
  '29.0',
  '52.0',
  '73.0',
  '40.0',
  '26.0',
  '70.0',
  '53.0',
  '22.0',
  '45.0',
  '50.0',
  '92.0',
  '25.0',
  '27.0',
  '21.0',
  '59.0',
  '16.0',
  '41',
  '59',
  '47',
  '46',
  '30',
  '53',
  '25',
  '20',
  '18.0',
  '12',
  '33',
  '55',
  '28.0',
  '36.0',
  '44',
  '20.0',
  '51.0',
  '19.0',
  '51',
  '57',
  '43',
  '52',
  '61',
  '45',
  '27',
  '28',
  '24',
  '35',
  '39',
  '22',
  '32',
  '49',
  '61.0',
  '34',
  '26',
  '75',
  '38',
  '48',
  '58',
  '16',
  '42',
  '37',
  '29',
  '21',
  '72',
  '56',
  '62',
  '40',
  '31',
  '74',
  '14',
  '50',
  '36',
  '63',
  '84.0',
  '54',
  '73',
  '54.0',
  '18',
  '23',
  '43.0',
  '6',
  '17',
  '67',
  '80.0',
  '30.0',
  '92',
  '66',
  '15.0',
  '81.0',
  '44.0',
  '0',
  '3',
  '60',
  '77',
  '85',
  '15',
  '64',
  '9',
  '13',
  '62.0',
  '23.0'])

In [9]:
genders = ["male", "unknown", "female"]

indices = df.index[df["Gender"].isin([x for x in df["Gender"].unique() if str(x)[0].isdigit()])].tolist()
print(len(indices))
for i in indices:
    age = df.at[i, "Patient age"]
    if str(age).lower() in genders:
        df.at[i, "Patient age"] = df.at[i, "Gender"]
        df.at[i, "Gender"] = age
df["Gender"].value_counts()

445

Gender
unknown    126872
Male        39090
Female      34546
unknowm        15
0               1
Name: count, dtype: int64

Still one entry is left. Let's see what's the issue.

In [10]:
df[df["Gender"]=="0"]

,Accession ID,Submission date,Virus name,Collection date,Location,Host,Additional location information,Sampling strategy,Gender,Patient age,Patient status,Last vaccinated,Passage,Specimen,Additional host information,Lineage,Clade,AA Substitutions
192363,EPI_ISL_7147154,2021-12-04,hCoV-19/USA/WY-WYPHL-20033054/2020,2020-06-26,North America / USA / Wyoming,Human,NaN,NaN,0,18,unknown,NaN,Original,NaN,NaN,B.1.166,GH,"(Spike_D574Y,NS3_Q57H,NSP12_P323L,Spike_D614G,..."

In [11]:
indices = df.index[df["Gender"].isin(["unknowm", "0"])].tolist()
df.loc[indices, "Gender"] = "unknown"
df["Gender"].value_counts()

Gender
unknown    126888
Male        39090
Female      34546
Name: count, dtype: int64

### Age

In [12]:
import re
from collections import defaultdict

def find_age_formats(df):
    # Identify regex patterns for different Patient age formats and show examples/counts
    ages = pd.Series(df["Patient age"].astype(str).fillna("").values).str.strip()
    unique_ages = pd.Series(ages.unique())

    patterns = {
        "integer_years": r'^\s*\d{1,3}\s*(?:y|yr|yrs|year|years)?\s*$',
        "decimal_years": r'^\s*\d+\.\d+\s*(?:y|yr|yrs|year|years)?\s*$',
        "months": r'^\s*\d{1,3}\s*(?:m|mo|mos|month|months)\b\.?$',
        "days": r'^\s*\d{1,3}\s*(?:d|day|days)\b\.?$',
        "age_range": r'^\s*(?:<\s*)?\d{1,3}\s*(?:-|–|to)\s*\d{1,3}\s*(?:y|yr|yrs|year|years)?\s*$',
        "decade_s": r'^\s*\d{2}s\s*$',
        "less_than": r'^\s*[<>]\s*\d{1,3}\s*(?:y|yr|yrs|year|years)?\s*$',
        "birth_year": r'^\s*(?:19|20)\d{2}\s*$',
        "text_labels": r'^\s*(?:newborn|neonate|infant|baby|child|teen(?:ager)?|adolescent|adult|elderly|senior|unknown|unk|n/?a|na|not available)\b',
    }

    compiled = {k: re.compile(v, re.I) for k, v in patterns.items()}

    matches = defaultdict(list)
    for val in unique_ages.dropna().astype(str):
        v = val.strip()
        matched = False
        for name, cre in compiled.items():
            if v and cre.search(v):
                matches[name].append(v)
                matched = True
        if not matched and v:
            matches["unmatched"].append(v)

    # Print summary: count and up to 10 examples for each pattern
    for name in list(compiled.keys()) + ["unmatched"]:
        vals = pd.Series(matches.get(name, [])).drop_duplicates()
        print(f"{name}: {len(vals)} unique matches")
        if len(vals) > 0:
            print(vals.head(10).tolist())
        print("-" * 60)

    # Optional: show top unmatched values to refine regexes
    if matches.get("unmatched"):
        unmatched_counts = ages[ages.isin(matches["unmatched"])].value_counts().head(30)
        print("Top unmatched values (sample counts):")
        print(unmatched_counts)
    
    return matches

In [13]:
matches = find_age_formats(df)

integer_years: 122 unique matches
['73', '56', '72', '32', '35', '27', '50', '45', '36', '30']
------------------------------------------------------------
decimal_years: 72 unique matches
['3.0', '27.0', '19.0', '66.0', '57.0', '69.0', '48.0', '59.0', '0.33', '76.0']
------------------------------------------------------------
months: 19 unique matches
['3 months', '6 months', '4 months', '10 months', '2 months', '7 months', '9 months', '11 months', '5 months', '1 month']
------------------------------------------------------------
days: 4 unique matches
['8 days', '10 days', '21 days', '27 days']
------------------------------------------------------------
age_range: 98 unique matches
['55-59', '30-40', '40-50', '60-70', '50-54', '60-64', '70-74', '80-84', '65-69', '31 - 40']
------------------------------------------------------------
decade_s: 6 unique matches
['70s', '80s', '90s', '50s', '20s', '60s']
------------------------------------------------------------
less_than: 12 unique matches
['>30', '>60', '>18', '>80', '>40', '>91', '>70', '>50', '>85', '>89']
------------------------------------------------------------
birth_year: 0 unique matches
------------------------------------------------------------
text_labels: 2 unique matches
['unknown', 'Unknown']
------------------------------------------------------------
unmatched: 26 unique matches
['nan', 'unknow', 'unkown', '2020-1954', '2020-1984', '2020-1979', '2020-1991', '2020-1994', '2020-1972', '2020-1985']
------------------------------------------------------------
Top unmatched values (sample counts):
unknow               119
nan                    5
unkown                 3
Male                   3
Female                 3
over 100               2
90+                    2
uknown                 2
2020-1984              1
2020-1954              1
2020-1985              1
2020-1972              1
2020-1994              1
2020-1991              1
2020-1979              1
17 years 9 months      1
8 weeks                1
1 month 14 days        1
5 years 4 months       1
4 weeks                1
2 weeks                1
12 years 6 moths       1
4 years 6 moths        1
2 years 11 months      1
X                      1
Unkown                 1
Name: count, dtype: int64

From the above analysis, we see that its either of the following formats:
- `Integer years`: Convert to `float` for consistency
- `Decimal years`: Convert to `float` for consistency
- `Months`: Divide by `12` to get the age in years (1 decimal places)
- `Days`: Since all are less than `30 days` we assign as `0.0` (age in years)
- `Age range`: Assign the mean age (in `age_range` in column, we retain age range and handle standarization)
- `Decade`: Assign the mean age (in `age_range` in column, we retain age range and handle standarization)
- `Greater than`: Assign the lower bound (in `age_range` in column, we retain age range and handle standarization)
- `Text`: They are just different cases of `unknown` so standardize to lower case
- `Unmatched formats`:
    - `nan`, `unkown`, `unknow`: Map to `unknown`
    - Others seem to be like a subtraction operation ==> perform subtraction and have the float value

In [14]:
df[df["Patient age"].isin(["Male", "Female"])]

,Accession ID,Submission date,Virus name,Collection date,Location,Host,Additional location information,Sampling strategy,Gender,Patient age,Patient status,Last vaccinated,Passage,Specimen,Additional host information,Lineage,Clade,AA Substitutions
153446,EPI_ISL_4404950,2021-09-22,hCoV-19/Argentina/PAIS-A0768/2020,2020-06-16,South America / Argentina / Buenos Aires / Ber...,Human,NaN,NaN,unknown,Male,unknown,NaN,Original,NaN,NaN,B.1.499,GH,"(NSP7_S25L,NS3_Q57H,NSP2_T85I,NSP14_A320V,N_S1..."
191444,EPI_ISL_4404965,2021-09-22,hCoV-19/Argentina/PAIS-A0778/2020,2020-06-22,South America / Argentina / Buenos Aires / Ber...,Human,NaN,NaN,unknown,Male,unknown,NaN,Original,NaN,NaN,B.1.499,GH,"(NSP7_S25L,NS3_Q57H,NSP2_T85I,NSP15_S147I,NSP1..."
190334,EPI_ISL_4220000,2021-09-15,hCoV-19/Mexico/CMX-INMEGEN-04-07-79/2020,2020-06-24,North America / Mexico / Mexico City,Human,NaN,NaN,unknown,Female,unknown,NaN,Original,Oropharyngeal swab,NaN,B.1.609,G,"(N_S37P,NSP12_P323L,Spike_D614G,NSP12_Q191R)"
192382,EPI_ISL_4219998,2021-09-15,hCoV-19/Mexico/CMX-INMEGEN-04-07-77/2020,2020-06-24,North America / Mexico / Mexico City,Human,NaN,NaN,unknown,Female,unknown,NaN,Original,Oropharyngeal swab,NaN,B.1.1.222,GR,"(Spike_T732A,N_R203K,N_G204R,NSP15_V172L,NSP13..."
192381,EPI_ISL_4219999,2021-09-15,hCoV-19/Mexico/CMX-INMEGEN-04-07-78/2020,2020-06-24,North America / Mexico / Mexico City,Human,NaN,NaN,unknown,Female,unknown,NaN,Original,Oropharyngeal swab,NaN,B.1.369,GH,"(N_S183Y,NS3_Q57H,NSP2_T85I,NSP12_P323L,Spike_..."
143812,EPI_ISL_4220060,2021-09-15,hCoV-19/Mexico/CMX-INMEGEN-04-07-181/2020,2020-07-02,North America / Mexico / Mexico City,Human,NaN,NaN,unknown,Male,unknown,NaN,Original,Oropharyngeal swab,NaN,B.1.189,G,"(NSP15_D128Y,NSP3_C55Y,NSP3_V1229F,NSP12_A449V..."

In [15]:
for i,row in df[df["Patient age"].isin(["Male", "Female"])].iterrows():
    if row["Gender"].lower() in ["nan", "unknown"]:
        df.at[i, "Gender"] = row["Patient age"]
        df.at[i, "Patient age"] = "unknown"

In [16]:
matches1 = find_age_formats(df)

integer_years: 122 unique matches
['73', '56', '72', '32', '35', '27', '50', '45', '36', '30']
------------------------------------------------------------
decimal_years: 72 unique matches
['3.0', '27.0', '19.0', '66.0', '57.0', '69.0', '48.0', '59.0', '0.33', '76.0']
------------------------------------------------------------
months: 19 unique matches
['3 months', '6 months', '4 months', '10 months', '2 months', '7 months', '9 months', '11 months', '5 months', '1 month']
------------------------------------------------------------
days: 4 unique matches
['8 days', '10 days', '21 days', '27 days']
------------------------------------------------------------
age_range: 98 unique matches
['55-59', '30-40', '40-50', '60-70', '50-54', '60-64', '70-74', '80-84', '65-69', '31 - 40']
------------------------------------------------------------
decade_s: 6 unique matches
['70s', '80s', '90s', '50s', '20s', '60s']
------------------------------------------------------------
less_than: 12 unique matches
['>30', '>60', '>18', '>80', '>40', '>91', '>70', '>50', '>85', '>89']
------------------------------------------------------------
birth_year: 0 unique matches
------------------------------------------------------------
text_labels: 2 unique matches
['unknown', 'Unknown']
------------------------------------------------------------
unmatched: 24 unique matches
['nan', 'unknow', 'unkown', '2020-1954', '2020-1984', '2020-1979', '2020-1991', '2020-1994', '2020-1972', '2020-1985']
------------------------------------------------------------
Top unmatched values (sample counts):
unknow               119
nan                    5
unkown                 3
over 100               2
90+                    2
uknown                 2
2020-1984              1
2020-1954              1
2020-1994              1
2020-1991              1
2020-1979              1
2020-1985              1
1 month 14 days        1
8 weeks                1
17 years 9 months      1
2020-1972              1
2 weeks                1
4 weeks                1
5 years 4 months       1
12 years 6 moths       1
2 years 11 months      1
4 years 6 moths        1
X                      1
Unkown                 1
Name: count, dtype: int64

In [17]:
def multi_unit_age(age:str):
    """
    Convert age strings with multiple units (e.g., "1 month 14 days") to age in years (float).
    Assumes 1 year = 12 months, 1 month = 30 days for conversion.
    """
    # Use the combined pattern with OR logic
    pattern = re.compile(
        # 1. Matches 'X years Y months' (looks for 'y' then 'm')
        r'^\s*(?P<years>\d+)\s*y\w*?\s*(?:[,;\-]?\s*)?(?P<val_months>\d+)\s*m\w*?\s*$'
        
        + '|' # OR 
        
        # 2. Matches 'X months Y days' (looks for 'm' then 'd')
        r'^\s*(?P<months>\d+)\s*m\w*?\s*(?:[,;\-]?\s*)?(?P<days>\d+)\s*d\w*?\s*$',
        re.I 
    )

    def calculate_total_years(duration_string):
        match = pattern.search(duration_string)
        
        if not match:
            return -1

        # Use a dictionary to easily check which group was captured (since OR groups return None for the unmatched side)
        data = match.groupdict()
        
        total_years = 0.0

        # --- Case 1: Years/Months Structure Matched ---
        if data['years'] is not None:
            # data['years'] is the first number (X), data['val_months'] is the second (Y)
            Y = int(data['years'])
            M = int(data['val_months'])
            
            # Calculation: Y + M/12
            total_years = Y + (M / 12.0)
            unit = "Years/Months"

        # --- Case 2: Months/Days Structure Matched ---
        elif data['months'] is not None:
            # data['months'] is the first number (X), data['days'] is the second (Y)
            M = int(data['months'])
            D = int(data['days'])
            
            # Calculation: M/12 + D/365.25 (using 365.25 days/year for accuracy)
            total_years = (M / 12.0) + (D / 365.25)
            unit = "Months/Days"
            
        else:
            # Should not happen if one of the OR conditions is met
            return f"Error: Failed to extract values from '{duration_string}'"

        return round(total_years, 1)
    return calculate_total_years(age)

In [18]:
matches = matches1
for i,row in df.iterrows():
    age = str(row["Patient age"]).strip()
    if age in matches["integer_years"] or age in matches["decimal_years"]:
        df.at[i, "Patient age"] = float(re.findall(r'\d+\.?\d*', age)[0])
    elif age in matches["text_labels"]:
        df.at[i, "Patient age"] = "unknown"
    elif age in matches["months"]:
        months = float(re.findall(r'\d+\.?\d*', age)[0])
        df.at[i, "Patient age"] = round(months / 12, 1)
    elif age in matches["days"]:
        days = float(re.findall(r'\d+\.?\d*', age)[0])
        df.at[i, "Patient age"] = 0.0
    elif age in matches["decade_s"]:
        decade = int(re.findall(r'\d{2}', age)[0])
        df.at[i, "Patient age"] = f"{decade}-{decade+9}"
    elif age in matches["less_than"]:
        val = float(age[1:])
        if age.startswith("<"):
            df.at[i, "Patient age"] = val - 5  # Assuming '< X' means X - 5 years
        elif age.startswith(">"):
            df.at[i, "Patient age"] = val + 5  # Assuming '> X' means X + 5 years
    elif age in matches["unmatched"]:
        if age.lower().startswith("u") or age == "nan" or age == 'X':
            df.at[i, "Patient age"] = "unknown"
        elif "-" in age:
            a,b = age.split("-") if "-" in age else age.split("to")
            if a == "2020":
                df.at[i, "Patient age"] = (float(a.strip()) - float(b.strip()))
            else:
                df.at[i, "Patient age"] = (float(a.strip()) + float(b.strip())) / 2
        elif "weeks" in age:
            weeks = float(re.findall(r'\d+\.?\d*', age)[0])
            df.at[i, "Patient age"] = round((weeks * 7) / 365, 1)
        elif "over" in age:
            val = float(re.findall(r'\d+\.?\d*', age)[0])
            print(age, val)
            df.at[i, "Patient age"] = val + 5  # Assuming 'over X' means X + 5 years
        elif "under" in age:
            val = float(re.findall(r'\d+\.?\d*', age)[0])
            print(age, val)
            df.at[i, "Patient age"] = val - 5  # Assuming 'under X' means X - 5 years
        elif multi_unit_age(age) != -1:
            val = multi_unit_age(age)
            print(age, val, "Success")
            df.at[i, "Patient age"] = val
        elif multi_unit_age(age) == -1 and re.match(r'^\s*\d{1,3}\s*+', age): # e.g. "90+"
            val = float(re.findall(r'\d+\.?\d*', age)[0])
            print(age, val)
            df.at[i, "Patient age"] = val + 5  # Assuming 'X+' means X + 5 years
    else:
        continue

over 100 100.0
1 month 14 days 0.1 Success
over 100 100.0
17 years 9 months 17.8 Success
90+ 90.0
5 years 4 months 5.3 Success
12 years 6 moths 12.5 Success
90+ 90.0
2 years 11 months 2.9 Success
4 years 6 moths 4.5 Success

In [19]:
find_age_formats(df)

integer_years: 0 unique matches
------------------------------------------------------------
decimal_years: 131 unique matches
['73.0', '56.0', '72.0', '32.0', '35.0', '27.0', '50.0', '45.0', '36.0', '30.0']
------------------------------------------------------------
months: 0 unique matches
------------------------------------------------------------
days: 0 unique matches
------------------------------------------------------------
age_range: 98 unique matches
['55-59', '30-40', '40-50', '60-70', '50-54', '60-64', '70-74', '80-84', '65-69', '31 - 40']
------------------------------------------------------------
decade_s: 0 unique matches
------------------------------------------------------------
less_than: 0 unique matches
------------------------------------------------------------
birth_year: 0 unique matches
------------------------------------------------------------
text_labels: 1 unique matches
['unknown']
------------------------------------------------------------
unmatched: 0 unique matches
------------------------------------------------------------

defaultdict(list,
            {'text_labels': ['unknown'],
             'decimal_years': ['73.0',
              '56.0',
              '72.0',
              '32.0',
              '35.0',
              '27.0',
              '50.0',
              '45.0',
              '36.0',
              '30.0',
              '62.0',
              '64.0',
              '39.0',
              '37.0',
              '47.0',
              '44.0',
              '46.0',
              '21.0',
              '61.0',
              '3.0',
              '57.0',
              '68.0',
              '41.0',
              '83.0',
              '29.0',
              '66.0',
              '38.0',
              '15.0',
              '49.0',
              '65.0',
              '25.0',
              '88.0',
              '34.0',
              '52.0',
              '58.0',
              '40.0',
              '24.0',
              '85.0',
              '43.0',
              '67.0',
              '33.0',
              '74.0',
              '20.0',
              '10.0',
              '63.0',
              '76.0',
              '87.0',
              '59.0',
              '54.0',
              '79.0',
              '70.0',
              '77.0',
              '28.0',
              '31.0',
              '69.0',
              '51.0',
              '71.0',
              '26.0',
              '53.0',
              '78.0',
              '60.0',
              '11.0',
              '42.0',
              '55.0',
              '48.0',
              '2.0',
              '23.0',
              '81.0',
              '6.0',
              '17.0',
              '9.0',
              '18.0',
              '19.0',
              '7.0',
              '75.0',
              '0.2',
              '5.0',
              '80.0',
              '22.0',
              '0.5',
              '91.0',
              '12.0',
              '0.3',
              '84.0',
              '8.0',
              '90.0',
              '95.0',
              '0.0',
              '86.0',
              '4.0',
              '16.0',
              '0.8',
              '96.0',
              '82.0',
              '89.0',
              '1.0',
              '13.0',
              '92.0',
              '14.0',
              '93.0',
              '94.0',
              '97.0',
              '100.0',
              '98.0',
              '99.0',
              '102.0',
              '0.6',
              '101.0',
              '136.0',
              '0.9',
              '0.33',
              '105.0',
              '0.4',
              '0.92',
              '104.0',
              '0.1',
              '120.0',
              '103.0',
              '0.7',
              '107.0',
              '17.8',
              '1.8',
              '5.3',
              '1.5',
              '2.5',
              '12.5',
              '2.9',
              '4.5',
              '3.8',
              '110.0',
              '1.6'],
             'age_range': ['55-59',
              '30-40',
              '40-50',
              '60-70',
              '50-54',
              '60-64',
              '70-74',
              '80-84',
              '65-69',
              '31 - 40',
              '85-88',
              '43-46',
              '40-43',
              '52-55',
              '73-76',
              '28-31',
              '67-70',
              '22-25',
              '64-67',
              '55-58',
              '49-52',
              '70-73',
              '16-19',
              '58-61',
              '37-40',
              '25-28',
              '19-22',
              '34-37',
              '10-20',
              '31-34',
              '46-49',
              '21 - 30',
              '51 - 60',
              '61 - 70',
              '61-64',
              '18 - 20',
              '82-85',
              '41 - 50',
              '81 - 90',
              '40-49',
              '20-30',
              '71 - 80',
              '70-79',
              '21-30',
              '31-40',
              '30-34',
              '25-29',
              '35-39',
              '60-69',
              '40-44',
              '75-79',
              '45-49',
              '50 to 59',
              '41-50',
              '51-60',
              '50-59',
              '91-100',
              '20-29',
              '79-82',
              '20-24',
              '71-80',
              '61-70',
              '40 to 49',
              '30-39',
              '30 to 39',
              '18-49',
              '80-89',
              '76-79',
              '60 to 69',
              '81-90',
              '91 - 100',
              '0-9',
              '50-64',
              '20 to 29',
              '90-94',
              '10-19',
              '51-40',
              '0 - 9',
              '88-91',
              '70 to 79',
              '90-99',
              '85-89',
              '20 - 29',
              '50 - 59',
              '30 - 39',
              '70 - 79',
              '5-9',
              '80 - 89',
              '90 - 99',
              '40 - 49',
              '60 - 69',
              '18-20',
              '10 - 19',
              '10-14',
              '11-20',
              '41- 50',
              '51- 60',
              '0-4']})

In [20]:
df["age_group"] = df["Patient age"].apply(map_age_to_group)
df["age_group"].value_counts()

age_group
unknown    196762
15-49        2103
50-69        1100
>70           548
5-14            7
<5              4
Name: count, dtype: int64

### Additonal host information

Let's see if we can fill in some missing values in other columns using `Additional host information` column

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200524 entries, 8434 to 200523
Data columns (total 19 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Accession ID                     200524 non-null  object
 1   Submission date                  200524 non-null  object
 2   Virus name                       200524 non-null  object
 3   Collection date                  200524 non-null  object
 4   Location                         200524 non-null  object
 5   Host                             200524 non-null  object
 6   Additional location information  6210 non-null    object
 7   Sampling strategy                11252 non-null   object
 8   Gender                           200524 non-null  object
 9   Patient age                      200524 non-null  object
 10  Patient status                   200509 non-null  object
 11  Last vaccinated                  76 non-null      object
 12  Passage                          200524 non-null  object
 13  Specimen                         66115 non-null   object
 14  Additional host information      2166 non-null    object
 15  Lineage                          200524 non-null  object
 16  Clade                            200521 non-null  object
 17  AA Substitutions                 200524 non-null  object
 18  age_group                        200524 non-null  object
dtypes: object(19)
memory usage: 34.6+ MB

In [22]:
sorted([str(x) for x in df["Additional host information"].unique()])

['-',
 '--',
 '01.03.-07.03.2020 skiing in Madona di Campiglio',
 'Active miner',
 'Acute Limphoblastic Leukemia',
 'Acute Lumphoblastic Leukemia',
 'Acute Lymphoblastic Leukemia',
 'Acute Lympoblastic Leukemia',
 'Acute lymphoblastic leukemia',
 'Additional disease: Hypertension',
 'Additional disease: Hypothyroid',
 'Additional diseases: Diabetes and Hypothyroid',
 'Asymptomatic Direct and High risk contact of confirmed case',
 'Austria',
 'Black African American',
 'Black African American, Hispanic',
 'Black African American, Non-Hispanic',
 'Breast cancer',
 'COPD, smoker, dry cough, fever, SPO2 72% on arrival, CXR: B/L infiltrates and pulmonary congestion',
 'COVID-19 positive case who entered from Brazil.',
 'COVID-19 positive case who entered from Canada.',
 'COVID-19 positive case who entered from Egypt.',
 'COVID-19 positive case who entered from France.',
 'COVID-19 positive case who entered from Great Britain (United Kingdom).',
 'COVID-19 positive case who entered from India.',
 'COVID-19 positive case who entered from Indonesia.',
 'COVID-19 positive case who entered from Ireland.',
 'COVID-19 positive case who entered from Italy.',
 'COVID-19 positive case who entered from Mexico.',
 'COVID-19 positive case who entered from Pakistan.',
 'COVID-19 positive case who entered from Philippines.',
 'COVID-19 positive case who entered from Saudi Arabia.',
 'COVID-19 positive case who entered from South Korea.',
 'COVID-19 positive case who entered from Spain.',
 'COVID-19 positive case who entered from Sweden.',
 'COVID-19 positive case who entered from USA.',
 'COVID-19 positive case who entered from United States.',
 'Cardiopathy',
 'Cardiopathy, Diabetes',
 'Cardiopathy, Diabetes, Hepatic',
 'Cardiopathy, Diabetes, Obesity',
 'Cardiopathy, Diabetes, Obesity, asthma',
 'Cardiopathy, Diabetes, Renal',
 'Case of reinfection, first sample is EPI_ISL_811148, second sample is EPI_ISL_811149',
 'Cell culture sample',
 'Close contact as a care worker',
 'Close contact as a home visit care worker',
 'Close contact person',
 'Come back from Wuhan',
 'Come back from Wuhan, China',
 'Confirmed',
 'Confirmed case of reinfection sample 1(related to sequence hCoV-19/Brazil/18116918_140/2021)',
 'Contact',
 'Contact with imported cases',
 'Contactant of a traveler returning from Dubai',
 'Culture supernatant',
 'DM type 2, progressive SOB, SPO2 88% in RA, high BP, CXR: B/L lung infiltrates and haziness >50% more on the RT side',
 'Diabetes mellitus type 1',
 'Diagnostic Testing',
 'Driver',
 'EHPAD 5 Sens',
 'EHPAD Mas Rome',
 'EHPAD Mas Rome caregiver',
 'Elderly',
 'Europe / Italy',
 'Exposed Donor',
 'Family infection',
 'Family-cluster transmission',
 'Father of the person who come back from Wuhan',
 'Female',
 'Fever, SOB, noisy chest, chest pain, cough, SPO2 >95% RA, chest: B/L wheeze. CXR: B/L haziness',
 'Fever, cough, pneumonia, CXR: bilateral infiltration',
 'Fever, pneumonia, CXR: bilateral infiltration / Retroperotonial hematoma',
 'First passage of the isolate obtained with hCoV-19/Iran/Q100/2020',
 'First passage of the isolate obtained with hCoV-19/Iran/Q111/2020',
 'First sample',
 'Foreign patient from Argentina',
 'Full genomes EPI_ISL_610237 and EPI_ISL_610238 were obtained from same patient at same time. It is a case of coinfection.',
 'Full genomes EPI_ISL_610237 and EPI_ISL_610238 were obtained from same patient at the same time. It is a case of double infection.',
 'Glioblastoma',
 'Grandson returns from Tokyo',
 'He traveled to Italy (16/02 a 23/02/2020)',
 'Health Worker',
 'Health care worker',
 'Health worker',
 'Healthcare Worker infected in hospital',
 'Healthcare worker',
 'Healthcare worker first wave',
 'Healthcare worker: Hospital employee',
 'Healthcare worker: Hospital worker',
 'High risk contact of confirmed case and first pregnant death',
 'Hispanic',
 'History of travelling abroad 4 days prior to the start of symptoms',
 'History of travelling abroad two weeks prior to the start of symptoms and contact with a suspect COVID-19 case at the work environment',
 'Holiday in Italy',
 'Hospital',
 'Hospital General Sur de Quito',
 'Hospital outbreak',
 'Hospital staff without symptom',
 'Housekeeper',
 'Husband and wife, no travel history; Contact with a confirmed case from Ningbo, Zhejiang on 1/27',
 'Hypertensive symptoms of cough and sore throat',
 'Import Italy, Sondrio, Madesimo 29.2.-.6.3.',
 'Imported case',
 'Imported case from Kazakhstan',
 'Imported case from Mexico',
 'Imported case from Netherlands',
 'Imported case from Philippines',
 'Imported case from USA',
 'Indian contact of Italian tourist',
 'Infected in France',
 'Infected in Iran',
 'Infected in N. Italy',
 'Infected in Switzerland',
 'Infected in U.K.',
 'Infected in U.S.A.',
 'Italian tourist in India',
 'Italy skiing with family in Trentino Vigo di Fassa 22-29. February, in contact with previously positive family member',
 'KE19',
 'KE20',
 'KE21',
 'KE23',
 'KE24',
 'KE25',
 'KE26',
 'Large oputbreak in a small village after dancing fest Kynice outbreak',
 'Longitudinal surveillance (repeat sampling)',
 'Lymphoblastic Leukemia, Diabetes, Trisomia 21',
 'Male',
 'Mother of HZCDC6948',
 'Neprotic Syndrome',
 'Neurological',
 'Non Healthcare Worker',
 'Non-Hispanic',
 'Not Screened for S Drop out',
 'Not Screened for S Drop out - RT',
 'Not Screened for S Dropout',
 'Not Screened for S Gene Dropout',
 'Not Screened for S Gene dropout',
 'Not Screened for S gene dropout',
 'Not Screened for the S Gene Dropout',
 'Not screened for S gene dropout',
 'Obesity',
 'Original sample hCoV-19/Brazil/RJ-FIOCRUZ-COV20/2020 | EPI_ISL_15515007',
 'Other, Hispanic',
 'Other, Non-Hispanic',
 'Other: Contact of another COVID-positive case COVID767',
 'Other: Contact of patient sample Covid537',
 'Other: Contact of patient sample Covid806',
 'Other: Reinfected',
 'Other: two contacts of this case (COVID 1158 and COVID1576) tested positive',
 'Outpatient',
 'Para-umbilical hernia. Chest infection, fever 39.5, cough, SOB, SPO2 85% in RA, blood acidosis, CXR: diffuse B/L infiltrates more in the left side,on mechanical ventilation',
 'Part of longitudinal sampling series related to EPI_ISL_527402',
 'Part of longitudinal sampling series related to EPI_ISL_527403',
 'Part of longitudinal sampling series related to EPI_ISL_527405',
 'Part of longitudinal sampling series related to EPI_ISL_527406',
 'Part of longitudinal sampling series related to EPI_ISL_527408',
 'Part of longitudinal sampling series related to EPI_ISL_527409',
 'Part of longitudinal sampling series related to EPI_ISL_527410',
 'Part of longitudinal sampling series related to EPI_ISL_527411',
 'Part of longitudinal sampling series related to EPI_ISL_527416,EPI_ISL_527417',
 'Part of longitudinal sampling series related to EPI_ISL_527416,EPI_ISL_527418',
 'Part of longitudinal sampling series related to EPI_ISL_527417,EPI_ISL_527418',
 'Part of longitudinal sampling series related to EPI_ISL_527419',
 'Part of longitudinal sampling series related to EPI_ISL_527420',
 'Part of longitudinal sampling series related to EPI_ISL_527421, EPI_ISL_527422',
 'Part of longitudinal sampling series related to EPI_ISL_527421, EPI_ISL_527423',
 'Part of longitudinal sampling series related to EPI_ISL_527422, EPI_ISL_527423',
 'Part of longitudinal sampling series related to EPI_ISL_527424',
 'Part of longitudinal sampling series related to EPI_ISL_527425',
 'Part of longitudinal sampling series related to EPI_ISL_527426',
 'Part of longitudinal sampling series related to EPI_ISL_527427',
 'Part of longitudinal sampling series related to EPI_ISL_527428, EPI_ISL_527429',
 'Part of longitudinal sampling series related to EPI_ISL_527428, EPI_ISL_527430',
 'Part of longitudinal sampling series related to EPI_ISL_527429, EPI_ISL_527430',
 'Part of longitudinal sampling series related to EPI_ISL_527431',
 'Part of longitudinal sampling series related to EPI_ISL_527432',
 'Part of longitudinal sampling series related to EPI_ISL_527434',
 'Part of longitudinal sampling series related to EPI_ISL_527435',
 'Part of longitudinal sampling series related to EPI_ISL_527436, EPI_ISL_527437',
 'Part of longitudinal sampling series related to EPI_ISL_527436, EPI_ISL_527438',
 'Part of longitudinal sampling series related to EPI_ISL_527437,EPI_ISL_527438',
 'Part of longitudinal sampling series related to EPI_ISL_527439',
 'Part of longitudinal sampling series related to EPI_ISL_527440',
 'Part of longitudinal sampling series related to EPI_ISL_527442, EPI_ISL_527444',
 'Part of longitudinal sampling series related to EPI_ISL_527442,EPI_ISL_527443',
 'Part of longitudinal sampling series related to EPI_ISL_527443 , EPI_ISL_527444',
 'Part of longitudinal sampling series related to EPI_ISL_527451',
 'Part of longitudinal sampling series related to EPI_ISL_527452',
 'Part of longitudinal sampling series related to EPI_ISL_527454',
 'Part of longitudinal sampling series related to EPI_ISL_527455',
 'Part of longitudinal sampling series related to EPI_ISL_527459,EPI_ISL_527460',
 'Part of longitudinal sampling series related to EPI_ISL_527459,EPI_ISL_527462',
 'Part of longitudinal sampling series related to EPI_ISL_527460,EPI_ISL_527462',
 'Part of longitudinal sampling series related to EPI_ISL_527461',
 'Part of longitudinal sampling series related to EPI_ISL_527463',
 'Part of longitudinal sampling series related to EPI_ISL_527464',
 'Part of longitudinal sampling series related to EPI_ISL_527465',
 'Part of longitudinal sampling series related to EPI_ISL_527466',
 'Part of longitudinal sampling series related to EPI_ISL_527467',
 'Part of longitudinal sampling series related to EPI_ISL_527468',
 'Part of longitudinal sampling series related to EPI_ISL_527469',
 'Part of longitudinal sampling series related to EPI_ISL_527470',
 'Part of longitudinal sampling series related to EPI_ISL_527471',
 'Part of longitudinal sampling series related to EPI_ISL_527475',
 'Part of longitudinal sampling series related to EPI_ISL_527476',
 'Part of longitudinal sampling series related to EPI_ISL_527479',
 'Part of longitudinal sampling series related to EPI_ISL_527480',
 'Part of longitudinal sampling series related to EPI_ISL_527483,EPI_ISL_527484',
 'Part of longitudinal sampling series related to EPI_ISL_527484,EPI_ISL_527485',
 'Part of longitudinal sampling series related to EPI_ISL_527485',
 'Patient acquired infection from community',
 'Patient acquired infection in congregation',
 'Patient came from Italy',
 'Patient came from Osaka',
 'Patient came from Philippine',
 'Patient came from Tokyo',
 'Patient co-infected with influenza B',
 'Patient from China (visiting Sri Lanka)',
 'Patient from Guadalajara',
 'Patient from Wuhan',
 'Patient from Wuhan, China',
 'Patient had contact with a positive case. Symptoms: cough.',
 'Patient had contact with a positive case. Symptoms: fever, general disconfort, headache.',
 'Patient had contact with a positive case. Symptoms: fever, general disconfort, muscle or joint pain, headache, cough.',
 'Patient has chronic renal problems. Symptoms: fever, general disconfort, muscle or joint pain, headache, cough, anosmia, rhinorrhea, dyspnoea.',
 'Patient has diabetes mellitus. No symptoms.',
 'Patient infected after a stopover in Brest',
 'Patient infected through contact with a confirmed case',
 'Patient infected while traveling in France',
 'Patient infected while traveling in Italy',
 'Patient infected while traveling in Japan',
 'Patient is a a health worker. Patient has Diabetes Mellitus, asthma, she is in corticosteroid treatment, she has arterial hypertension. Symptoms: general disconfort, cough, dyspnoea, subcostal draw.',
 'Patient return form Wuhan, China',
 'Patient seeking diagnosis at Centre',
 'Patient started taking medicine 2 days before sampling',
 'Patient visited the homes of infected people',
 'Patient was using the same care home as the infected person',
 'Patient with chronic respiratory diseases',
 'Patient with severe combined immunodeficiency (SCID)',
 'Patient_2 timepoint-1',
 'Patient_4 timepoint-1',
 'Pneumonia (Chest X-ray, CT)',
 'Pneumonia / Respiratory Distress',
 'Pneumonia / Respiratory Failure',
 'Pregnant',
 'Putative import from Italy, region Sondrio, city Madesimo, stay 29.2. - 6.3.2020',
 'Putative import from Switzerland, Fils',
 'Quarantine',
 'Re-infection sample first sample ”FUNED_09.21-RI-MG” second sample ”FUNED_10.21-RI-MG”',
 'Reduced level of consciousness, generalized fatigue, vomiting, intubated, Ketoacidosis, CXR: fair entry B/L',
 'Reinfection',
 'Reinfection case first episode: hCoV-19/Brazil/SC-FIOCRUZ-34450-R1/2020, second episode: hCoV-19/Brazil/SC-FIOCRUZ-4334-R2/2022.',
 'Reinfection case, first episode. Second episode EPI_ISL_9571709.',
 'Reinfection case, first episode. Second episode hCoV-19/Brazil/RJ-FIOCRUZ-13336-R2/2022',
 'Reinfection case, first episode. Second episode hCoV-19/Brazil/RJ-FIOCRUZ-13338-R2/2022',
 'Reinfection case, first episode. Second episode hCoV-19/Brazil/RJ-FIOCRUZ-13343-R2/2022.',
 'Reinfection case, first episode. Second episode hCoV-19/Brazil/RJ-FIOCRUZ-13348-R2/2022.',
 'Reinfection case, first episode. Second episode hCoV-19/Brazil/RJ-FIOCRUZ-13352-R2/2022.',
 'Reinfection case, first episode. Second episode hCoV-19/Brazil/RJ-FIOCRUZ-13355-R2/2022.',
 'Reinfection case, first episode. Second episode hCoV-19/Brazil/RJ-FIOCRUZ-1499-R2/2022',
 'Reinfection case, first episode. Second episode: hCoV-19/Brazil/PR-FIOCRUZ-33811-R2/2020',
 'Reinfection case. First sample, second sample hCoV-19/Brazil/PR-FIOCRUZ-21069-R2/2021',
 'Relatives who attended the same wedding in Hubei province (1/15 – 1/24)',
 'Reported case of reinfection (1st infection EPI_ISL_514673, 2nd infection EPI_ISL_514674)',
 'Reported case of reinfection (1st infection EPI_ISL_516798 2nd infection EPI_ISL_516799)',
 'Reported case of reinfection (1st infection EPI_ISL_523507, 2nd infection EPI_ISL_523510)',
 'Reported case of reinfection (1st infection EPI_ISL_525430, 2nd infection EPI_ISL_516650)',
 'Reported case of reinfection (1st infection EPI_ISL_636834 , 2nd infection EPI_ISL_636835 )',
 'Reported case of reinfection (1st infection EPI_ISL_636836 , 2nd infection EPI_ISL_636837 )',
 'Reported case of reinfection (1st infection EPI_ISL_708529, 2nd infection EPI_ISL_708530)',
 'Reported case of reinfection (1st infection EPI_ISL_756293, 2nd infection EPI_ISL_756294)',
 'Reported case of reinfection (1st infection EPI_ISL_792561, 2nd infection EPI_ISL_792562)',
 'Resident Parnaiba, Piaui, Brazil',
 'Resident of Arizona; Tested in New Mexico',
 'Resident of Arizona; tested in New Mexico',
 'Resident of Texas; Tested in New Mexico',
 'Resident of Texas; tested in New Mexico',
 'Resident of Wuhan; Traveled to Shaoxing on 1/17',
 'Russian Federation, Orenburg',
 'Same patient serial clinical specimem S01 (hCoV-19/Brazil/PR-FIOCRUZ-10634/2020 - S01)',
 'Same patient serial clinical specimem S01 (hCoV-19/Brazil/RJ-FIOCRUZ-7747A3/2020 - S02)',
 'Same patient serial clinical specimem S02 (hCoV-19/Brazil/PR-FIOCRUZ-11162/2020 - S02)',
 'Same patient serial clinical specimem S02 (hCoV-19/Brazil/RJ-FIOCRUZ-7657/2020 - S01)',
 'Sample related with hCoV-19/India/MH-IGIB-A2/2020',
 'Sample related with hCoV-19/India/MH-IGIB-B2/2020',
 'Sample related with hCoV-19/India/MH-IGIB-C2/2020',
 'Sample related with hCoV-19/India/MH-IGIB-D2/2020',
 'Samples related: hCoV-19/USA/DC-HP13074-PIDHNGFDXK/2020, hCoV-19/USA/DC-HP13075-PIDHNGFDXK/2020',
 'Samples related: hCoV-19/USA/MD-HP06744-PIDVASJNVN/2020',
 'Samples related: hCoV-19/USA/MD-HP06747-PIDZOIGLYH/2020, hCoV-19/USA/MD-HP10126-PIDZOIGLYH/2020',
 'Samples related: hCoV-19/USA/MD-HP06747-PIDZOIGLYH/2020, hCoV-19/USA/MD-HP10127-PIDZOIGLYH/2020',
 'Samples related: hCoV-19/USA/MD-HP07254-PIDYTVDNUF/2020',
 'Samples related: hCoV-19/USA/MD-HP07289-PIDVFMDKTB/2020',
 'Samples related: hCoV-19/USA/MD-HP07354-PIDYZDIUXI/2020',
 'Samples related: hCoV-19/USA/MD-HP09782-PIDMUYDGWO/2020, hCoV-19/USA/MD-HP09960-PIDMUYDGWO/2020, hCoV-19/USA/MD-HP09961-PIDMUYDGWO/2020',
 'Samples related: hCoV-19/USA/MD-HP09782-PIDMUYDGWO/2020, hCoV-19/USA/MD-HP09960-PIDMUYDGWO/2020, hCoV-19/USA/MD-HP10151-PIDMUYDGWO/2020',
 'Samples related: hCoV-19/USA/MD-HP09782-PIDMUYDGWO/2020, hCoV-19/USA/MD-HP09961-PIDMUYDGWO/2020, hCoV-19/USA/MD-HP10151-PIDMUYDGWO/2020',
 'Samples related: hCoV-19/USA/MD-HP09960-PIDMUYDGWO/2020, hCoV-19/USA/MD-HP09961-PIDMUYDGWO/2020, hCoV-19/USA/MD-HP10151-PIDMUYDGWO/2020',
 'Samples related: hCoV-19/USA/MD-HP13034-PIDFEOASBK/2020',
 'Samples related: hCoV-19/USA/MD-HP13035-PIDFEOASBK/2020',
 'Samples related: hCoV-19/USA/MD-HP13040-PIDHCPHTBW/2020',
 'Samples related: hCoV-19/USA/MD-HP13041-PIDHCPHTBW/2020',
 'Samples related: hCoV-19/USA/MD-HP13043-PIDDKWPWUP/2020',
 'Samples related: hCoV-19/USA/MD-HP13044-PIDRDYJIQW/2020',
 'Samples related: hCoV-19/USA/MD-HP13048-PIDPSLQNZF/2020',
 'Samples related: hCoV-19/USA/MD-HP13068-PIDFTUQFAV/2020, hCoV-19/USA/MD-HP13137-PIDFTUQFAV/2020',
 'Samples related: hCoV-19/USA/MD-HP13068-PIDFTUQFAV/2020, hCoV-19/USA/MD-HP13137-PIDFTUQFAV/2020, hCoV-19/USA/MD-HP13140-PIDFTUQFAV/2020',
 'Samples related: hCoV-19/USA/MD-HP13076-PIDLYROPCD/2020, hCoV-19/USA/MD-HP13077-PIDLYROPCD/2020',
 'Samples related: hCoV-19/USA/MD-HP13081-PIDAQPUTDA/2020',
 'Samples related: hCoV-19/USA/MD-HP13096-PIDRDYJIQW/2020',
 'Samples related: hCoV-19/USA/MD-HP13140-PIDFTUQFAV/2020, hCoV-19/USA/MD-HP13068-PIDFTUQFAV/2020',
 'Samples related: hCoV-19/USA/MD-HP13140-PIDFTUQFAV/2020, hCoV-19/USA/MD-HP13137-PIDFTUQFAV/2020',
 'Samples related: hCoV-19/USA/MD-HP13144-PIDLYROPCD/2020, hCoV-19/USA/MD-HP13077-PIDLYROPCD/2020',
 'Samples related: hCoV-19/USA/MD-HP13153-PIDAQPUTDA/2020',
 'Samples related: hCoV-19/USA/MD-HP22681-PIDVKFNJPC/2021',
 'Samples related: hCoV-19/USA/MD-HP30631-PIDIZQEUJZ/2020',
 'Samples related: hCoV-19/USA/MD-HP34034-PIDCNATNLN/2020',
 'Samples related: hCoV-19/USA/MD-HP38172-PIDFAOJXFY/2020',
 'Samples related: hCoV-19/USA/MD-HP38881-PIDMGKSILR/2020',
 'Screened for S gene dropout',
 'Second passage of the isolate obtained with hCoV-19/Iran/Q100/2020',
 'Second passage of the isolate obtained with hCoV-19/Iran/Q111/2020',
 'Severe productive cough, SOB, wheeze, SPO2 90% in RA, generalized fatigue and tiredness, sore throat, CXR: B/L infiltrates',
 'Suspect',
 'Suspected case',
 'Suspects to be infected in recent trip to Guayaquil',
 'Symptoms begun on 09-03-2020.',
 'Symptoms: fever, general disconfort, headache, cough, odynophagia, rhinorrhea.',
 'Symptoms: fever, general disconfort, headache, cough.',
 'Symptoms: fever, general disconfort, muscle or joint pain, headache, cough, anosmia, rhinorrhea.',
 'Symptoms: fever, headache, rhinorrhea.',
 'Symptoms: fever, vomiting or diarrhea, dyspnoea.',
 'Symptoms: general disconfort, headache, cough.',
 'Symptoms: general disconfort, muscle or joint pain, headache, cough, anosmia.',
 'Syntomps begun on 05-03-2020.',
 'Syntomps begun on 09-03-2020. Arrival to Mexico on 06-03-20',
 'Syphilis',
 'Tranplant Patient',
 'Traveled to Hubei (1/11 – 1/24); Mother and grandmother were confirmed cases',
 'Traveled to Hubei (1/16 – 1/23)',
 'United Arab Emirates',
 'Unknown source of infection',
 'Virus isolates from hCoV-19/Brazil/RJ-FIOCRUZ-4368A1/2020',
 'White',
 'White, Hispanic',
 'White, Non-Hispanic',
 'XLA-immunocompromised patient with prolonged SARS-CoV-2 infection',
 '`',
 'atrioventricular connection',
 'case1 day0',
 'case2 day0',
 'case3 day0',
 'close contact of UC34',
 'community case',
 'community transmission',
 'dysmorphological syndrome',
 'e.g. Patient infected while traveling in ….',
 'first case of ”community transmission” in the US; reported Feb 26, 2020',
 'first infection',
 'gastroschisis post surgery',
 'health care worker',
 'health care worker taking care of UC4 (EPI_ISL_413561)',
 'household contact of UC13 (EPI_ISL_417317)',
 'household contact of workplace case',

There are few rows where Gender is missing and this `Additional host information` column has the gender. Let's fix it.

In [23]:
for i,row in df[df["Additional host information"].isin(["Male", "Female"])].iterrows():
    if row["Gender"] == "unknown":
        df.at[i, "Gender"] = row["Additional host information"]

Next, we see a few `'-'`, `'--'`, ``'`'``, `'unknown'`. Let's standardize them to `'unknown'`.

In [24]:
df["Additional host information"].fillna("unknown", inplace=True)

In [25]:
for i,row in df[df["Additional host information"].isin(['-', '--', 'unknown', '`'])].iterrows():
    df.at[i, "Additional host information"] = "unknown"
df[df["Additional host information"].isin(['-', '--', 'unknown', '`'])]["Additional host information"].value_counts()

Additional host information
unknown    199360
Name: count, dtype: int64

In [26]:
sorted([str(x).lower() for x in df["Additional host information"].unique()])

['01.03.-07.03.2020 skiing in madona di campiglio',
 'active miner',
 'acute limphoblastic leukemia',
 'acute lumphoblastic leukemia',
 'acute lymphoblastic leukemia',
 'acute lymphoblastic leukemia',
 'acute lympoblastic leukemia',
 'additional disease: hypertension',
 'additional disease: hypothyroid',
 'additional diseases: diabetes and hypothyroid',
 'asymptomatic direct and high risk contact of confirmed case',
 'atrioventricular connection',
 'austria',
 'black african american',
 'black african american, hispanic',
 'black african american, non-hispanic',
 'breast cancer',
 'cardiopathy',
 'cardiopathy, diabetes',
 'cardiopathy, diabetes, hepatic',
 'cardiopathy, diabetes, obesity',
 'cardiopathy, diabetes, obesity, asthma',
 'cardiopathy, diabetes, renal',
 'case of reinfection, first sample is epi_isl_811148, second sample is epi_isl_811149',
 'case1 day0',
 'case2 day0',
 'case3 day0',
 'cell culture sample',
 'close contact as a care worker',
 'close contact as a home visit care worker',
 'close contact of uc34',
 'close contact person',
 'come back from wuhan',
 'come back from wuhan, china',
 'community case',
 'community transmission',
 'confirmed',
 'confirmed case of reinfection sample 1(related to sequence hcov-19/brazil/18116918_140/2021)',
 'contact',
 'contact with imported cases',
 'contactant of a traveler returning from dubai',
 'copd, smoker, dry cough, fever, spo2 72% on arrival, cxr: b/l infiltrates and pulmonary congestion',
 'covid-19 positive case who entered from brazil.',
 'covid-19 positive case who entered from canada.',
 'covid-19 positive case who entered from egypt.',
 'covid-19 positive case who entered from france.',
 'covid-19 positive case who entered from great britain (united kingdom).',
 'covid-19 positive case who entered from india.',
 'covid-19 positive case who entered from indonesia.',
 'covid-19 positive case who entered from ireland.',
 'covid-19 positive case who entered from italy.',
 'covid-19 positive case who entered from mexico.',
 'covid-19 positive case who entered from pakistan.',
 'covid-19 positive case who entered from philippines.',
 'covid-19 positive case who entered from saudi arabia.',
 'covid-19 positive case who entered from south korea.',
 'covid-19 positive case who entered from spain.',
 'covid-19 positive case who entered from sweden.',
 'covid-19 positive case who entered from united states.',
 'covid-19 positive case who entered from usa.',
 'culture supernatant',
 'diabetes mellitus type 1',
 'diagnostic testing',
 'dm type 2, progressive sob, spo2 88% in ra, high bp, cxr: b/l lung infiltrates and haziness >50% more on the rt side',
 'driver',
 'dysmorphological syndrome',
 'e.g. patient infected while traveling in ….',
 'ehpad 5 sens',
 'ehpad mas rome',
 'ehpad mas rome caregiver',
 'elderly',
 'europe / italy',
 'exposed donor',
 'family infection',
 'family-cluster transmission',
 'father of the person who come back from wuhan',
 'female',
 'fever, cough, pneumonia, cxr: bilateral infiltration',
 'fever, pneumonia, cxr: bilateral infiltration / retroperotonial hematoma',
 'fever, sob, noisy chest, chest pain, cough, spo2 >95% ra, chest: b/l wheeze. cxr: b/l haziness',
 'first case of ”community transmission” in the us; reported feb 26, 2020',
 'first infection',
 'first passage of the isolate obtained with hcov-19/iran/q100/2020',
 'first passage of the isolate obtained with hcov-19/iran/q111/2020',
 'first sample',
 'foreign patient from argentina',
 'full genomes epi_isl_610237 and epi_isl_610238 were obtained from same patient at same time. it is a case of coinfection.',
 'full genomes epi_isl_610237 and epi_isl_610238 were obtained from same patient at the same time. it is a case of double infection.',
 'gastroschisis post surgery',
 'glioblastoma',
 'grandson returns from tokyo',
 'he traveled to italy (16/02 a 23/02/2020)',
 'health care worker',
 'health care worker',
 'health care worker taking care of uc4 (epi_isl_413561)',
 'health worker',
 'health worker',
 'healthcare worker',
 'healthcare worker first wave',
 'healthcare worker infected in hospital',
 'healthcare worker: hospital employee',
 'healthcare worker: hospital worker',
 'high risk contact of confirmed case and first pregnant death',
 'hispanic',
 'history of travelling abroad 4 days prior to the start of symptoms',
 'history of travelling abroad two weeks prior to the start of symptoms and contact with a suspect covid-19 case at the work environment',
 'holiday in italy',
 'hospital',
 'hospital general sur de quito',
 'hospital outbreak',
 'hospital staff without symptom',
 'household contact of uc13 (epi_isl_417317)',
 'household contact of workplace case',
 'housekeeper',
 'husband and wife, no travel history; contact with a confirmed case from ningbo, zhejiang on 1/27',
 'hypertensive symptoms of cough and sore throat',
 'import italy, sondrio, madesimo 29.2.-.6.3.',
 'imported case',
 'imported case from kazakhstan',
 'imported case from mexico',
 'imported case from netherlands',
 'imported case from philippines',
 'imported case from usa',
 'indian contact of italian tourist',
 'infected in france',
 'infected in iran',
 'infected in n. italy',
 'infected in switzerland',
 'infected in u.k.',
 'infected in u.s.a.',
 'infection case first episode / seconde sample (1651296)',
 'italian tourist in india',
 'italy skiing with family in trentino vigo di fassa 22-29. february, in contact with previously positive family member',
 'ke19',
 'ke20',
 'ke21',
 'ke23',
 'ke24',
 'ke25',
 'ke26',
 'large oputbreak in a small village after dancing fest kynice outbreak',
 'long-term foster care',
 'longitudinal surveillance (repeat sampling)',
 'lymphoblastic leukemia, diabetes, trisomia 21',
 'male',
 'mother of hzcdc6948',
 'neogenetic single kindey',
 'neprotic syndrome',
 'neurological',
 'non healthcare worker',
 'non-hispanic',
 'not screened for s drop out',
 'not screened for s drop out - rt',
 'not screened for s dropout',
 'not screened for s gene dropout',
 'not screened for s gene dropout',
 'not screened for s gene dropout',
 'not screened for s gene dropout',
 'not screened for the s gene dropout',
 'obesity',
 'obesity, hypertension, neurological disorder',
 'original sample hcov-19/brazil/rj-fiocruz-cov20/2020 | epi_isl_15515007',
 'other, hispanic',
 'other, non-hispanic',
 'other: contact of another covid-positive case covid767',
 'other: contact of patient sample covid537',
 'other: contact of patient sample covid806',
 'other: reinfected',
 'other: two contacts of this case (covid 1158 and covid1576) tested positive',
 'outgoing traveler',
 'outpatient',
 'para-umbilical hernia. chest infection, fever 39.5, cough, sob, spo2 85% in ra, blood acidosis, cxr: diffuse b/l infiltrates more in the left side,on mechanical ventilation',
 'part of longitudinal sampling series related to epi_isl_527402',
 'part of longitudinal sampling series related to epi_isl_527403',
 'part of longitudinal sampling series related to epi_isl_527405',
 'part of longitudinal sampling series related to epi_isl_527406',
 'part of longitudinal sampling series related to epi_isl_527408',
 'part of longitudinal sampling series related to epi_isl_527409',
 'part of longitudinal sampling series related to epi_isl_527410',
 'part of longitudinal sampling series related to epi_isl_527411',
 'part of longitudinal sampling series related to epi_isl_527416,epi_isl_527417',
 'part of longitudinal sampling series related to epi_isl_527416,epi_isl_527418',
 'part of longitudinal sampling series related to epi_isl_527417,epi_isl_527418',
 'part of longitudinal sampling series related to epi_isl_527419',
 'part of longitudinal sampling series related to epi_isl_527420',
 'part of longitudinal sampling series related to epi_isl_527421, epi_isl_527422',
 'part of longitudinal sampling series related to epi_isl_527421, epi_isl_527423',
 'part of longitudinal sampling series related to epi_isl_527422, epi_isl_527423',
 'part of longitudinal sampling series related to epi_isl_527424',
 'part of longitudinal sampling series related to epi_isl_527425',
 'part of longitudinal sampling series related to epi_isl_527426',
 'part of longitudinal sampling series related to epi_isl_527427',
 'part of longitudinal sampling series related to epi_isl_527428, epi_isl_527429',
 'part of longitudinal sampling series related to epi_isl_527428, epi_isl_527430',
 'part of longitudinal sampling series related to epi_isl_527429, epi_isl_527430',
 'part of longitudinal sampling series related to epi_isl_527431',
 'part of longitudinal sampling series related to epi_isl_527432',
 'part of longitudinal sampling series related to epi_isl_527434',
 'part of longitudinal sampling series related to epi_isl_527435',
 'part of longitudinal sampling series related to epi_isl_527436, epi_isl_527437',
 'part of longitudinal sampling series related to epi_isl_527436, epi_isl_527438',
 'part of longitudinal sampling series related to epi_isl_527437,epi_isl_527438',
 'part of longitudinal sampling series related to epi_isl_527439',
 'part of longitudinal sampling series related to epi_isl_527440',
 'part of longitudinal sampling series related to epi_isl_527442, epi_isl_527444',
 'part of longitudinal sampling series related to epi_isl_527442,epi_isl_527443',
 'part of longitudinal sampling series related to epi_isl_527443 , epi_isl_527444',
 'part of longitudinal sampling series related to epi_isl_527451',
 'part of longitudinal sampling series related to epi_isl_527452',
 'part of longitudinal sampling series related to epi_isl_527454',
 'part of longitudinal sampling series related to epi_isl_527455',
 'part of longitudinal sampling series related to epi_isl_527459,epi_isl_527460',
 'part of longitudinal sampling series related to epi_isl_527459,epi_isl_527462',
 'part of longitudinal sampling series related to epi_isl_527460,epi_isl_527462',
 'part of longitudinal sampling series related to epi_isl_527461',
 'part of longitudinal sampling series related to epi_isl_527463',
 'part of longitudinal sampling series related to epi_isl_527464',
 'part of longitudinal sampling series related to epi_isl_527465',
 'part of longitudinal sampling series related to epi_isl_527466',
 'part of longitudinal sampling series related to epi_isl_527467',
 'part of longitudinal sampling series related to epi_isl_527468',
 'part of longitudinal sampling series related to epi_isl_527469',
 'part of longitudinal sampling series related to epi_isl_527470',
 'part of longitudinal sampling series related to epi_isl_527471',
 'part of longitudinal sampling series related to epi_isl_527475',
 'part of longitudinal sampling series related to epi_isl_527476',
 'part of longitudinal sampling series related to epi_isl_527479',
 'part of longitudinal sampling series related to epi_isl_527480',
 'part of longitudinal sampling series related to epi_isl_527483,epi_isl_527484',
 'part of longitudinal sampling series related to epi_isl_527484,epi_isl_527485',
 'part of longitudinal sampling series related to epi_isl_527485',
 'patient acquired infection from community',
 'patient acquired infection in congregation',
 'patient came from italy',
 'patient came from osaka',
 'patient came from philippine',
 'patient came from tokyo',
 'patient co-infected with influenza b',
 'patient from china (visiting sri lanka)',
 'patient from guadalajara',
 'patient from wuhan',
 'patient from wuhan, china',
 'patient had contact with a positive case. symptoms: cough.',
 'patient had contact with a positive case. symptoms: fever, general disconfort, headache.',
 'patient had contact with a positive case. symptoms: fever, general disconfort, muscle or joint pain, headache, cough.',
 'patient has chronic renal problems. symptoms: fever, general disconfort, muscle or joint pain, headache, cough, anosmia, rhinorrhea, dyspnoea.',
 'patient has diabetes mellitus. no symptoms.',
 'patient infected after a stopover in brest',
 'patient infected through contact with a confirmed case',
 'patient infected while traveling in france',
 'patient infected while traveling in italy',
 'patient infected while traveling in japan',
 'patient is a a health worker. patient has diabetes mellitus, asthma, she is in corticosteroid treatment, she has arterial hypertension. symptoms: general disconfort, cough, dyspnoea, subcostal draw.',
 'patient return form wuhan, china',
 'patient seeking diagnosis at centre',
 'patient started taking medicine 2 days before sampling',
 'patient visited the homes of infected people',
 'patient was using the same care home as the infected person',
 'patient with chronic respiratory diseases',
 'patient with severe combined immunodeficiency (scid)',
 'patient_2 timepoint-1',
 'patient_4 timepoint-1',
 'pneumonia (chest x-ray, ct)',
 'pneumonia / respiratory distress',
 'pneumonia / respiratory failure',
 'pregnant',
 'primary patient sample',
 'probably infected at a concert in the o2 arena - prague',
 'probably infected during a holiday in italy; mild respiratory signs',
 'putative import from italy, region sondrio, city madesimo, stay 29.2. - 6.3.2020',
 'putative import from switzerland, fils',
 'quarantine',
 're-infection sample first sample ”funed_09.21-ri-mg” second sample ”funed_10.21-ri-mg”',
 'reduced level of consciousness, generalized fatigue, vomiting, intubated, ketoacidosis, cxr: fair entry b/l',
 'refseq hcov-19/wuhan/wiv04/2019|gisaid accession no. epi_isl_402124',
 'reinfection',
 'reinfection case first episode: hcov-19/brazil/sc-fiocruz-34450-r1/2020, second episode: hcov-19/brazil/sc-fiocruz-4334-r2/2022.',
 'reinfection case, first episode. second episode epi_isl_9571709.',
 'reinfection case, first episode. second episode hcov-19/brazil/rj-fiocruz-13336-r2/2022',
 'reinfection case, first episode. second episode hcov-19/brazil/rj-fiocruz-13338-r2/2022',
 'reinfection case, first episode. second episode hcov-19/brazil/rj-fiocruz-13343-r2/2022.',
 'reinfection case, first episode. second episode hcov-19/brazil/rj-fiocruz-13348-r2/2022.',
 'reinfection case, first episode. second episode hcov-19/brazil/rj-fiocruz-13352-r2/2022.',
 'reinfection case, first episode. second episode hcov-19/brazil/rj-fiocruz-13355-r2/2022.',
 'reinfection case, first episode. second episode hcov-19/brazil/rj-fiocruz-1499-r2/2022',
 'reinfection case, first episode. second episode: hcov-19/brazil/pr-fiocruz-33811-r2/2020',
 'reinfection case. first sample, second sample hcov-19/brazil/pr-fiocruz-21069-r2/2021',
 'relatives who attended the same wedding in hubei province (1/15 – 1/24)',
 'renal tubular acidosis',
 'reported case of reinfection (1st infection epi_isl_514673, 2nd infection epi_isl_514674)',
 'reported case of reinfection (1st infection epi_isl_516798 2nd infection epi_isl_516799)',
 'reported case of reinfection (1st infection epi_isl_523507, 2nd infection epi_isl_523510)',
 'reported case of reinfection (1st infection epi_isl_525430, 2nd infection epi_isl_516650)',
 'reported case of reinfection (1st infection epi_isl_636834 , 2nd infection epi_isl_636835 )',
 'reported case of reinfection (1st infection epi_isl_636836 , 2nd infection epi_isl_636837 )',
 'reported case of reinfection (1st infection epi_isl_708529, 2nd infection epi_isl_708530)',
 'reported case of reinfection (1st infection epi_isl_756293, 2nd infection epi_isl_756294)',
 'reported case of reinfection (1st infection epi_isl_792561, 2nd infection epi_isl_792562)',
 'resident of arizona; tested in new mexico',
 'resident of arizona; tested in new mexico',
 'resident of texas; tested in new mexico',
 'resident of texas; tested in new mexico',
 'resident of wuhan; traveled to shaoxing on 1/17',
 'resident parnaiba, piaui, brazil',
 'russian federation, orenburg',
 'same patient as for sequence epi_isl_583427',
 'same patient as for sequence epi_isl_583428',
 'same patient as for sequence epi_isl_583431',
 'same patient as for sequence epi_isl_583439',
 'same patient as for sequence epi_isl_583444',
 'same patient as for sequence epi_isl_583447',
 'same patient as for sequence epi_isl_583456',
 'same patient as for sequence epi_isl_583461',
 'same patient as for sequence epi_isl_583466',
 'same patient as for sequence epi_isl_583469',
 'same patient as for sequence epi_isl_583475',
 'same patient as for sequence epi_isl_583479',
 'same patient serial clinical specimem s01 (hcov-19/brazil/pr-fiocruz-10634/2020 - s01)',
 'same patient serial clinical specimem s01 (hcov-19/brazil/rj-fiocruz-7747a3/2020 - s02)',
 'same patient serial clinical specimem s02 (hcov-19/brazil/pr-fiocruz-11162/2020 - s02)',
 'same patient serial clinical specimem s02 (hcov-19/brazil/rj-fiocruz-7657/2020 - s01)',
 'sample obtained 1 hour after birth',
 'sample related with hcov-19/india/mh-igib-a2/2020',
 'sample related with hcov-19/india/mh-igib-b2/2020',
 'sample related with hcov-19/india/mh-igib-c2/2020',
 'sample related with hcov-19/india/mh-igib-d2/2020',
 'samples related: hcov-19/usa/dc-hp13074-pidhngfdxk/2020, hcov-19/usa/dc-hp13075-pidhngfdxk/2020',
 'samples related: hcov-19/usa/md-hp06744-pidvasjnvn/2020',
 'samples related: hcov-19/usa/md-hp06747-pidzoiglyh/2020, hcov-19/usa/md-hp10126-pidzoiglyh/2020',
 'samples related: hcov-19/usa/md-hp06747-pidzoiglyh/2020, hcov-19/usa/md-hp10127-pidzoiglyh/2020',
 'samples related: hcov-19/usa/md-hp07254-pidytvdnuf/2020',
 'samples related: hcov-19/usa/md-hp07289-pidvfmdktb/2020',
 'samples related: hcov-19/usa/md-hp07354-pidyzdiuxi/2020',
 'samples related: hcov-19/usa/md-hp09782-pidmuydgwo/2020, hcov-19/usa/md-hp09960-pidmuydgwo/2020, hcov-19/usa/md-hp09961-pidmuydgwo/2020',
 'samples related: hcov-19/usa/md-hp09782-pidmuydgwo/2020, hcov-19/usa/md-hp09960-pidmuydgwo/2020, hcov-19/usa/md-hp10151-pidmuydgwo/2020',
 'samples related: hcov-19/usa/md-hp09782-pidmuydgwo/2020, hcov-19/usa/md-hp09961-pidmuydgwo/2020, hcov-19/usa/md-hp10151-pidmuydgwo/2020',
 'samples related: hcov-19/usa/md-hp09960-pidmuydgwo/2020, hcov-19/usa/md-hp09961-pidmuydgwo/2020, hcov-19/usa/md-hp10151-pidmuydgwo/2020',
 'samples related: hcov-19/usa/md-hp13034-pidfeoasbk/2020',
 'samples related: hcov-19/usa/md-hp13035-pidfeoasbk/2020',
 'samples related: hcov-19/usa/md-hp13040-pidhcphtbw/2020',
 'samples related: hcov-19/usa/md-hp13041-pidhcphtbw/2020',
 'samples related: hcov-19/usa/md-hp13043-piddkwpwup/2020',
 'samples related: hcov-19/usa/md-hp13044-pidrdyjiqw/2020',
 'samples related: hcov-19/usa/md-hp13048-pidpslqnzf/2020',
 'samples related: hcov-19/usa/md-hp13068-pidftuqfav/2020, hcov-19/usa/md-hp13137-pidftuqfav/2020',
 'samples related: hcov-19/usa/md-hp13068-pidftuqfav/2020, hcov-19/usa/md-hp13137-pidftuqfav/2020, hcov-19/usa/md-hp13140-pidftuqfav/2020',
 'samples related: hcov-19/usa/md-hp13076-pidlyropcd/2020, hcov-19/usa/md-hp13077-pidlyropcd/2020',
 'samples related: hcov-19/usa/md-hp13081-pidaqputda/2020',
 'samples related: hcov-19/usa/md-hp13096-pidrdyjiqw/2020',
 'samples related: hcov-19/usa/md-hp13140-pidftuqfav/2020, hcov-19/usa/md-hp13068-pidftuqfav/2020',
 'samples related: hcov-19/usa/md-hp13140-pidftuqfav/2020, hcov-19/usa/md-hp13137-pidftuqfav/2020',
 'samples related: hcov-19/usa/md-hp13144-pidlyropcd/2020, hcov-19/usa/md-hp13077-pidlyropcd/2020',
 'samples related: hcov-19/usa/md-hp13153-pidaqputda/2020',
 'samples related: hcov-19/usa/md-hp22681-pidvkfnjpc/2021',
 'samples related: hcov-19/usa/md-hp30631-pidizqeujz/2020',
 'samples related: hcov-19/usa/md-hp34034-pidcnatnln/2020',
 'samples related: hcov-19/usa/md-hp38172-pidfaojxfy/2020',
 'samples related: hcov-19/usa/md-hp38881-pidmgksilr/2020',
 'screened for s gene dropout',
 'second passage of the isolate obtained with hcov-19/iran/q100/2020',
 'second passage of the isolate obtained with hcov-19/iran/q111/2020',
 'sensory motor mononeuropathy',
 'severe productive cough, sob, wheeze, spo2 90% in ra, generalized fatigue and tiredness, sore throat, cxr: b/l infiltrates',
 'suspect',
 'suspected case',

### Patient status

Many entries seem to have some information about patient status. Let's see if these can be used to fill in missing patient status values.

In [27]:
df["Patient status"].fillna("unknown", inplace=True)
mask = df["Patient status"].astype(str).str.lower().str.startswith("unk")
df.loc[mask, "Patient status"] = "unknown"

First let's see the cases of `"reinfection"`, `"re-infection"`, or `"reinfected"`

In [28]:
# Get unique additional host information values (lowercased) and keep those containing "reinfection"
variations = ["reinfection", "reinfected", "re-infection"]
reinf = [v for v in pd.Series(df["Additional host information"].dropna().astype(str)).str.lower().unique() if any(var in v for var in variations)]
df[df["Additional host information"].str.lower().isin(reinf)]["Patient status"].value_counts()

Patient status
unknown         20
Live             6
Released         4
Reinfection      1
Hospitalized     1
Name: count, dtype: int64

In [29]:
mask = (df["Additional host information"].str.lower().isin(reinf)) & (df["Patient status"].str.lower() == "unknown")
df.loc[mask, "Patient status"] = "Reinfection"
df[df["Additional host information"].str.lower().isin(reinf)]["Patient status"].value_counts()

Patient status
Reinfection     21
Live             6
Released         4
Hospitalized     1
Name: count, dtype: int64

Next, let's match all the variations of patient status in the `Additional host information` column

In [30]:
# Status: 'Outpatient'
op_terms = ['outpatient']
for i,row in df[df["Additional host information"].str.lower().isin([x.lower() for x in op_terms])].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Outpatient"

# Status: 'asymptomatic direct and high risk contact of confirmed case'
for i,row in df[df["Additional host information"].str.lower().str.contains("asymptomatic direct and high risk contact of confirmed case", na=False)].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Asymptomatic, Suscpected (High Risk Contact)"

# Status: Confirmed/live/Case1
confirmed = ['case1 day0', 'case2 day0', 'case3 day0', 'confirmed', 'patient acquired infection from community', 'patient acquired infection in congregation',
             'first infection', 'family infection', 'family-cluster transmission', 'e.g. patient infected while traveling in ….', 'works at airport, acquired from community',
             'unknown source of infection']
for i,row in df[df["Additional host information"].str.lower().isin([x.lower() for x in confirmed])].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Infected"
part_match = ['infection', 'infected', 'patient infected', 'infected in', 'imported case from', 'covid-19 positive', 'community case', 'community transmission',]
for i,row in df[df["Additional host information"].str.lower().str.contains("|".join(part_match), na=False)].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Infected"

# Status: EHPAD
ehpad_terms = ['ehpad 5 sens', 'ehpad mas rome']
for i,row in df[df["Additional host information"].str.lower().isin([x.lower() for x in ehpad_terms])].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "EHPAD"

# Status: Hospitalized
hospitalized_terms = ['hospital', 'hospital general sur de quito']
for i,row in df[df["Additional host information"].str.lower().isin([x.lower() for x in hospitalized_terms])].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Hospitalized"

# Status: Suspected
suspected_terms = ['close contact as a care worker', 'close contact as a home visit care worker', 'close contact of uc34', 'close contact person', 'come back from wuhan', 'come back from wuhan, china', 'contact', 'contact with imported cases', 'contactant of a traveler returning from dubai',
 'copd, smoker, dry cough, fever, spo2 72% on arrival, cxr: b/l infiltrates and pulmonary congestion', 'exposed donor', 'fever, cough, pneumonia, cxr: bilateral infiltration', 'fever, pneumonia, cxr: bilateral infiltration / retroperotonial hematoma', 'fever, sob, noisy chest, chest pain, cough, spo2 >95% ra, chest: b/l wheeze. cxr: b/l haziness', 'first case of ”community transmission” in the us; reported feb 26, 2020', 'grandson returns from tokyo', 'he traveled to italy (16/02 a 23/02/2020)', 'high risk contact of confirmed case and first pregnant death', 'history of travelling abroad 4 days prior to the start of symptoms', 'history of travelling abroad two weeks prior to the start of symptoms and contact with a suspect covid-19 case at the work environment', 'household contact of uc13 (epi_isl_417317)', 'household contact of workplace case', 'housekeeper', 'husband and wife, no travel history; contact with a confirmed case from ningbo, zhejiang on 1/27', 'hypertensive symptoms of cough and sore throat', 'import italy, sondrio, madesimo 29.2.-.6.3.', 'indian contact of italian tourist', 'italian tourist in india', 'italy skiing with family in trentino vigo di fassa 22-29. february, in contact with previously positive family member', 'large oputbreak in a small village after dancing fest kynice outbreak', 'other: contact of another covid-positive case covid767', 'other: contact of patient sample covid537', 'other: contact of patient sample covid806', 'other: two contacts of this case (covid 1158 and covid1576) tested positive', 'outgoing traveler', 'patient came from italy', 'patient came from osaka', 'patient came from philippine', 'patient came from tokyo', 'patient co-infected with influenza b', 'patient from china (visiting sri lanka)', 'patient from guadalajara', 'patient from wuhan', 'patient from wuhan, china', 'patient had contact with a positive case. symptoms: cough.', 'patient had contact with a positive case. symptoms: fever, general disconfort, headache.', 'patient had contact with a positive case. symptoms: fever, general disconfort, muscle or joint pain, headache, cough.', 'patient has chronic renal problems. symptoms: fever, general disconfort, muscle or joint pain, headache, cough, anosmia, rhinorrhea, dyspnoea.', 'patient has diabetes mellitus. no symptoms.', 'patient return form wuhan, china', 'patient visited the homes of infected people', 'patient was using the same care home as the infected person', 'patient with chronic respiratory diseases', 'patient with severe combined immunodeficiency (scid)', 'probably infected at a concert in the o2 arena - prague', 'probably infected during a holiday in italy; mild respiratory signs', 'severe productive cough, sob, wheeze, spo2 90% in ra, generalized fatigue and tiredness, sore throat, cxr: b/l infiltrates', 'suspect', 'suspected case', 'suspects to be infected in recent trip to guayaquil', 'symptoms begun on 09-03-2020.', 'symptoms: fever, general disconfort, headache, cough, odynophagia, rhinorrhea.', 'symptoms: fever, general disconfort, headache, cough.', 'symptoms: fever, general disconfort, muscle or joint pain, headache, cough, anosmia, rhinorrhea.', 'symptoms: fever, headache, rhinorrhea.', 'symptoms: fever, vomiting or diarrhea, dyspnoea.', 'symptoms: general disconfort, headache, cough.', 'symptoms: general disconfort, muscle or joint pain, headache, cough, anosmia.', 'syntomps begun on 05-03-2020.', 'syntomps begun on 09-03-2020. arrival to mexico on 06-03-20', 'traveled to hubei (1/11 – 1/24); mother and grandmother were confirmed cases', 'traveled to hubei (1/16 – 1/23)']
for i,row in df[df["Additional host information"].str.lower().isin([x.lower() for x in suspected_terms])].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Suspected"

# Status: Healthcare worker
hcw_terms = ['ehpad mas rome caregiver', 'health care worker', 'health care worker', 'health care worker taking care of uc4 (epi_isl_413561)',
 'health worker', 'health worker', 'healthcare worker', 'healthcare worker first wave', 'healthcare worker infected in hospital', 'healthcare worker: hospital employee', 'healthcare worker: hospital worker', 'hospital staff without symptom']
for i,row in df[df["Additional host information"].str.lower().isin([x.lower() for x in hcw_terms])].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Healthcare worker"

# Status: Comorbidities
comorb = ['acute limphoblastic leukemia', 'acute lumphoblastic leukemia', 'acute lymphoblastic leukemia', 'acute lymphoblastic leukemia', 'acute lympoblastic leukemia', 'additional disease: hypertension', 'additional disease: hypothyroid', 'additional diseases: diabetes and hypothyroid', 'atrioventricular connection', 'breast cancer', 'cardiopathy', 'cardiopathy, diabetes', 'cardiopathy, diabetes, hepatic', 'cardiopathy, diabetes, obesity', 'cardiopathy, diabetes, obesity, asthma', 'cardiopathy, diabetes, renal', 'diabetes mellitus type 1', 'dm type 2, progressive sob, spo2 88% in ra, high bp, cxr: b/l lung infiltrates and haziness >50% more on the rt side', 'dysmorphological syndrome', 'gastroschisis post surgery', 'glioblastoma', 'lymphoblastic leukemia, diabetes, trisomia 21', 'neogenetic single kindey', 'neprotic syndrome', 'neurological', 'obesity', 'obesity, hypertension, neurological disorder', 'para-umbilical hernia. chest infection, fever 39.5, cough, sob, spo2 85% in ra, blood acidosis, cxr: diffuse b/l infiltrates more in the left side,on mechanical ventilation', 'patient has diabetes mellitus. no symptoms.', 'renal tubular acidosis', 'sensory motor mononeuropathy', 'syphilis', 'thinness', 'xla-immunocompromised patient with prolonged sars-cov-2 infection']
for i,row in df[df["Additional host information"].str.lower().isin([x.lower() for x in comorb])].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Comorbidities (more info in Additional host information)"

# Status: Pneumonia
pneu_terms = ['pneumonia (chest x-ray, ct)', 'pneumonia / respiratory distress', 'pneumonia / respiratory failure']
for i,row in df[df["Additional host information"].str.lower().isin([x.lower() for x in pneu_terms])].iterrows():
    if row["Patient status"].lower() == "unknown":
        df.at[i, "Patient status"] = "Pneumonia (more info in Additional host information)"

Now, that we have filled in most entries, let's derive four new features from this: `clinical_status`, `hospitalization_status`, `severity`, `who_category`

In [31]:
df = map_pat_status(df, df_pat, "clinical_status")
df = map_pat_status(df, df_pat, "hospitalization_status")
df = map_pat_status(df, df_pat, "severity")
df = map_pat_status(df, df_pat, "who_category")

In [32]:
df["clinical_status"].value_counts(), df["hospitalization_status"].value_counts(), df["severity"].value_counts(), df["who_category"].value_counts()

(clinical_status
 unknown       183261
 active         12841
 recovered       2263
 dead            1119
 suspected        565
 recovered?         6
 Name: count, dtype: int64,
 hospitalization_status
 unknown                                        184327
 no                                               9485
 yes                                              6208
 usually yes - requires higher level of care        18
 usually yes                                        12
 yes by default                                      4
 ususally no                                         1
 Name: count, dtype: int64,
 severity
 unknown                           183805
 mild                                8671
 moderate                            4051
 uninfected                          2269
 dead                                1119
 severe                               118
 unknown - need +RNA to confirm        21
 likely severe?                         1
 Name: count, dtype: int64,
 who_category
 Unknown                  186915
 Ambulatory mild            4944
 Hospitalized moderate      4502
 Uninfected                 2269
 Dead                       1119
 Hospitalized severe         306
 Name: count, dtype: int64)

### Location

Split location into `continent`, `country`, `state` and `city`

In [34]:
# Vectorized split and strip (much faster than iterrows)
parts = df["Location"].astype(str).str.split("/", n=3, expand=True)
parts = parts.rename(columns={0: "continent", 1: "country", 2: "state", 3: "city"})
# strip whitespace and replace empty strings with NaN
for c in parts.columns:
    parts[c] = parts[c].where(parts[c].notna(), np.nan).astype(object)
    parts[c] = parts[c].str.strip().replace({"": np.nan})

# Assign new location columns directly (avoid relying on `cols` variable)
df[["continent", "country", "state", "city"]] = parts[["continent", "country", "state", "city"]]
df.drop(columns=["Location"], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200524 entries, 8434 to 200523
Data columns (total 26 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Accession ID                     200524 non-null  object
 1   Submission date                  200524 non-null  object
 2   Virus name                       200524 non-null  object
 3   Collection date                  200524 non-null  object
 4   Host                             200524 non-null  object
 5   Additional location information  6210 non-null    object
 6   Sampling strategy                11252 non-null   object
 7   Gender                           200524 non-null  object
 8   Patient age                      200524 non-null  object
 9   Patient status                   200524 non-null  object
 10  Last vaccinated                  76 non-null      object
 11  Passage                          200524 non-null  object
 12  Specimen                         66115 non-null   object
 13  Additional host information      200524 non-null  object
 14  Lineage                          200524 non-null  object
 15  Clade                            200521 non-null  object
 16  AA Substitutions                 200524 non-null  object
 17  age_group                        200524 non-null  object
 18  clinical_status                  200055 non-null  object
 19  hospitalization_status           200055 non-null  object
 20  severity                         200055 non-null  object
 21  who_category                     200055 non-null  object
 22  continent                        200524 non-null  object
 23  country                          200524 non-null  object
 24  state                            186578 non-null  object
 25  city                             52584 non-null   object
dtypes: object(26)
memory usage: 45.3+ MB

Let's see if we can infer more from `Additional location information` column

In [37]:
sorted([str(x).lower() for x in df["Additional location information"].unique()])

['(mc donalds, cínovecká 796, praha 8)',
 '(mcdonald, praha 8)',
 '(the hospital for chronic disease bohnice)',
 '1160.0',
 '1170.0',
 '1180.0',
 '1200.0',
 '1340.0',
 '1970.0',
 '1st settlement',
 '300 bed hospital',
 '3080.0',
 '3090.0',
 '91331',
 '91942',
 '91942.0',
 '92021',
 '92026',
 '92102.0',
 '92103.0',
 '92105.0',
 '92109.0',
 '92110',
 '92110.0',
 '92114',
 '92117',
 '92117.0',
 '92121.0',
 '92126.0',
 '92231',
 '92243',
 'a passenger in nile river cruise ship',
 'accra',
 'ada county',
 'agualva',
 'agualva cacem',
 'aguas livres',
 'alajuela',
 'alajuela, orotina',
 'alajuela, san rafael',
 'algueirão-mem martins',
 'amadora',
 'amajuba',
 'army base camp',
 'aroub',
 'asia / china / wuhan',
 'asia / south korea / gwangju',
 'ausilio mutuo',
 'awa indigenous community',
 'balata',
 'betacoronavirus',
 'bethlehem',
 'bezmialem vakif university hospital',
 'bolzano, italy',
 'bordeaux',
 'buraca',
 'burgenland, austria',
 'cairo',
 'cairo university (abol-reesh) pediatric hospital (cusph) mounira, cairo',
 'casal de cambra',
 'castellammare di stabia/napoli',
 'central labs',
 'chu-stp',
 'city suburb',
 'civil hospital',
 'civil hospital, panchkula',
 'civil hospital, ropar',
 'clermont_ferrand',
 'clinical hospital of ribeirão preto',
 'cms',
 'cms, roorkee',
 'community acquired infection',
 'comunidad waorani',
 'contact',
 'contact of hcov-19/brazil/spbr-01/2020',
 'contact to patient from wuhan',
 'corrois',
 'cova da moura',
 'cruise ship',
 'cruise_ship_1',
 'cruise_ship_2',
 'cubatao-sp, brazil',
 'curridabat',
 'damaia de cima',
 'demerdash hospital',
 'demerdash hospital',
 'der hatab',
 'diamond princess cruise ship',
 'division_exposure: california',
 'dusseldorf health department',
 'düsseldorf health department',
 'e.g. cruise ship, convention, live animal market',
 'el sharkia',
 'el zawia',
 'encosta de sol',
 'escazu',
 'esic medical college and hospital',
 'esic medical college and hospital, faridabad',
 'ethekwini',
 'europe / croatia / zagreb',
 'europe / france / haut-rhin / kembs',
 'europe / france / haut-rhin / mulhouse',
 'europe / france / haut-rhin / rixheim',
 'europe / france / haut-rhin / st-louis',
 'europe / germany / baden-württemberg / lörrach',
 'europe / germany / baden-württemberg / weil am rhein',
 'europe / germany / saxony / hohenwarsleben',
 'europe / italy / cruise ship',
 'europe / italy / south tyrol',
 'europe / serbia / cuprija',
 'europe / serbia / kragujevac',
 'europe / serbia / krusevac',
 'europe / united kingdom / england',
 'ex italy',
 'ezzahra',
 'falagueria- venda nova',
 'fawwar',
 'giza',
 'grand princess 1st cruise',
 'grand princess 2nd cruise',
 'grand princess cruise ship',
 'grand princess cruise ship',
 'grecia',
 'halhoul',
 'hebron',
 'heliopolis',
 'helsinki and uusimaa hospital district',
 'heredia',
 'heredia, san rafael',
 'hgp iess',
 'home',
 'hospital',
 'hospital das clinicas de ribeirão preto',
 'hospital das clínicas de ribeirão preto',
 'hospital especialidades',
 'hospital general de mexico',
 'hospital general sur de quito',
 'hospital pablo arturo suarez',
 'hospital rscm',
 'hospital universitari germans trias i pujol',
 'hospital vilardebó',
 'huoqiu county first people`s hospital',
 'huoqiu county first people’s hospital',
 'huoqiu county frist people`s hospital',
 'huoqiu’ county first people’s hospital',
 'huoshan county first people’s hospital',
 'huoshan county hospital',
 'huoshan county people`s hospital',
 'huoshan people`s hospital',
 'ibra',
 'idsp unit',
 'idsp unit, dehradun',
 'ilembe',
 'import from austria, hollabrunn',
 'import from austria, salzburg - bad gastein hotel haas',
 'import from ukraine',
 'imported',
 'imported case',
 'imported case from bangladesh',
 'imported case from canada',
 'imported case from france',
 'imported case from japan',
 'imported case from kazakhstan',
 'imported case from kazakhstan',
 'imported case from kuwait',
 'imported case from kyrgyzstan',
 'imported case from mexico',
 'imported case from mexico',
 'imported case from netherlands',
 'imported case from pakistan',
 'imported case from philippines',
 'imported case from philippines',
 'imported case from russia',
 'imported case from united arab emirates',
 'imported case from united kingdom',
 'imported case from united states',
 'imported case from usa',
 'imported from europe',
 'imported from germany',
 'imported from puerto rico',
 'imported from spain',
 'imported from usa',
 'indian citizen sampled at iran',
 'indian contact of italian tourist',
 'indian national sampled at iran',
 'indonesian citizen visit to india',
 'industrial enterprises in liberec',
 'infected during religious event in france',
 'international conveyance: cruise ship: grand princess mexico',
 'iran',
 'iressef diamniadio / ds khombole',
 'iressef diamniadio / ds thies',
 'iressef diamniadio / ds tivaouane',
 'ischgl, austria',
 'italian tourist',
 'jackson memorial hospital',
 'jatrabari',
 'jerusalem',
 'jinzhai county people`s hospital',
 'jinzhai county people’s hospital',
 'jinzhai’ county people’s hospital',
 'kaohsiung city',
 'king cetshwayo',
 'klinik kesihatan batu, pejabat kesihatan kepong',
 'kuantan',
 'labcorp',
 'lagos, nimr drive-through testing centre',
 'lapcorp',
 'lapland hospital district',
 'large oputbreak in a small village after dancing fest kynice outbreak',
 'large outbreak locality, infected from a friend in the local brewery',
 'local',
 'local case',
 'local from airport',
 'local from health',
 'local from police',
 'local from social',
 'local from unknow',
 'lower austria, austria',
 'lu`an people`s hospital',
 'lu’an people’s hospital',
 'lu’an’ people’s hospital',
 'majdal ben fadel',
 'mcdonald praha - ďáblice',
 'menofia',
 'mina da agua',
 'monte abrão',
 'mutrah',
 'nablus',
 'nan',
 'narayanganj high school',
 'national influenza centre, nphl, kathmandu, nepal',
 'new cairo',
 'nicvd',
 'nilmrc',
 'nimr drive-through testing centre',
 'nitor',
 'no travel history',
 'nocera inferiore/salerno',
 'north america / panama / bocas del toro / changuinola',
 'north america / panama / bocas del toro / miramar',
 'north america / panama / chiriqui / chiriqui',
 'north america / panama / chiriqui / david',
 'north america / panama / cocle / rio hato',
 'north america / panama / colon / nueva esperanza',
 'north america / panama / darien / la palma',
 'north america / panama / darien / yaviza',
 'north america / panama / guna yala / aliganda',
 'north america / panama / guna yala / belisario porras',
 'north america / panama / guna yala / nargana',
 'north america / panama / los santos / las tablas',
 'north america / panama / metropolitana / don bosco',
 'north america / panama / metropolitana / pedregal',
 'north america / panama / metropolitana / taurustuna',
 'north america / panama / panama norte / alcalde diaz',
 'north america / panama / panama norte / chilibre',
 'north america / panama / panama oeste / arraijan',
 'north america / panama / panama oeste / barrio balboa',
 'north america / panama / panama oeste / barrio colon',
 'north america / panama / panama oeste / veracruz',
 'north america / panama / san miguelito / alcalde diaz',
 'north america / panama / veraguas / sona',
 'north america / panama / veraguas / veraguas',
 'north america / usa / district of columbia',
 'north america / usa / maryland',
 'north america / usa / new york',
 'north america / usa / north carolina',
 'north america / usa / virginia',
 'north america / usa / washington dc',
 'nursing home establishments for aged and dependent individuals',
 'obur hospital',
 'okd darkov',
 'originally from thane, maharashtra',
 'other:',
 'other: 92093',
 'other: 92122',
 'other: 99999',
 'other: ada',
 'other: ada',
 'other: africa / canary islands / las palmas de gran canaria',
 'other: aguas maravilhosas',
 'other: allegheny county',
 'other: antananarivo - a&c hotel',
 'other: aroeira',
 'other: bairro da gloria',
 'other: barra de macae',
 'other: barramares',
 'other: bei resources control nr-52509 provided as extracted dna after several passages',
 'other: bela vista',
 'other: blaine',
 'other: botafogo',
 'other: breede valley, wocester',
 'other: breede valley, worcester',
 'other: calabarzon',
 'other: cancela preta',
 'other: canyon',
 'other: cape town',
 'other: car',
 'other: cavaleiros',
 'other: central luzon',
 'other: changamwe',
 'other: chris hani district municipality',
 'other: chu-stp',
 'other: city of johannesburg metro region f',
 'other: clinic',
 'other: contact of another covid-positive case',
 'other: corrego do ouro',
 'other: day care facility',
 'other: drakenstein, paarl',
 'other: ds popenguine',
 'other: ds thies',
 'other: ds tivaouane',
 'other: eastern, blue downs',
 'other: eastern, eerste river',
 'other: eastern, macassar',
 'other: eastern, somerset west',
 'other: eelderwolde',
 'other: elmore',
 'other: engelbert',
 'other: engenho da praia',
 'other: epi isl 2933956, epi isl 2933960',
 'other: erp',
 'other: esenyurt',
 'other: fenoarivo',
 'other: figueira',
 'other: fronteira',
 'other: gieten',
 'other: groningen',
 'other: halacho',
 'other: hoogezand',
 'other: hospital',
 'other: hospital na plesi, czech republic',
 'other: hospitalized patient',
 'other: huitieme',
 'other: imbetiba',
 'other: imported case',
 'other: imported case (france-senegal)',
 'other: imported case (london-istanbul-dakar)',
 'other: imported case (madrid-dakar)',
 'other: imported case from kazakhstan',
 'other: imported case from mexico',
 'other: imported case from netherlands',
 'other: imported case from philippines',
 'other: imported case from russia',
 'other: imported case from usa',
 'other: indian national sampled at iran',
 'other: ispecimen, inc.',
 'other: jardim carioca ii',
 'other: jardim franco',
 'other: jardim vitoria',
 'other: kanasin',
 'other: kepez',
 'other: khayelitsha',
 'other: kilifi',
 'other: laboratory',
 'other: lagoa',
 'other: lagomar',
 'other: lagomar',
 'other: live in ireland. he was in brazil to visit his parents',
 'other: madri, suica, zurick, saint mortiz (07/03 a 15/03/2020)',
 'other: malvinas',
 'other: mandya',
 'other: medical college of wisconsin',
 'other: merida',
 'other: metro',
 'other: metro region b',
 'other: metro region d',
 'other: metro region f',
 'other: miramar',
 'other: montefiori health system',
 'other: morro santana',
 'other: muratpasa',
 'other: nairobi',
 'other: ncr',
 'other: nimr',
 'other: northeastern ohio',
 'other: northern, durbanville',
 'other: northern, kraaifontein',
 'other: northern, milnerton',
 'other: nova esperanca',
 'other: nova holanda',
 'other: nova malvina',
 'other: novo eldorado',
 'other: nursing home',
 'other: obala',
 'other: olamze',
 'other: oldenhove',
 'other: olomoucký kraj',
 'other: ospedale maggiore di parma',
 'other: owyhee',
 'other: parque aeroporto',
 'other: parque uniao',
 'other: party',
 'other: patient had travel history in the past months',
 'other: paulínia',
 'other: payette',
 'other: piracema',
 'other: port reitz',
 'other: postcode 6230',
 'other: pq santa monica',
 'other: praia campista',
 'other: praia do pecado',
 'other: reinfection/salvador',
 'other: residence',
 'other: riveira fluminense',
 'other: rush university medical center',
 'other: sao marcos',
 'other: satkania',
 'other: serik',
 'other: sol e mar',
 'other: spain / extremadura / caceres',
 'other: spain / extremadura / herrera del duque',
 'other: ten post',
 'other: timucuy',
 'other: tizimin',
 'other: trapiche',
 'other: travel history',
 'other: tygerberg, bellville',
 'other: tygerberg, bishop lavis',
 'other: tygerberg, delft',
 'other: tygerberg, elsies river',
 'other: tygerberg, parow',
 'other: verdes mares',
 'other: vila badejo',
 'other: visconde de araujo',
 'other: western, atlantis',
 'other: witzenberg, ceres',
 'other: zuidhorn',
 'other: zuidlaren',
 'other:ciudad delgado',
 'other:el porvenir',
 'other:ilopango',
 'other:mejicanos',
 'other:san marcos',
 'other:san salvador',
 'other:santa ana',
 'other:soyapango',
 'other:zacatecoluca',
 'others : las tablas',
 'others : unknown',
 'others : veraguas',
 'out of state',
 'pagani/salerno',
 'panama city',
 'panama/bocas del toro/calidonia',
 'panama/bocas del toro/changuinola',
 'panama/bocas del toro/el empalme',
 'panama/bocas del toro/las tablas',
 'panama/chiriqui/david',
 'panama/chiriqui/david',
 'panama/chiriqui/gomez',
 'panama/chiriqui/na',
 'panama/chiriqui/puerto armuelles',
 'panama/chiriqui/volcan',
 'panama/cocle/aguadulce',
 'panama/cocle/anton',
 'panama/cocle/chiguiri arriba',
 'panama/cocle/el coco',
 'panama/cocle/el valle',
 'panama/cocle/llano grande',
 'panama/cocle/pajonal',
 'panama/cocle/penonome',
 'panama/cocle/penonome',
 'panama/cocle/rio hato',
 'panama/cocle/rio hato',
 'panama/cocle/toabre',
 'panama/colon/barrio colon',
 'panama/colon/barrio norte',
 'panama/colon/barrio norte',
 'panama/colon/barrio sur',
 'panama/colon/buena vista',
 'panama/colon/cativa',
 'panama/colon/ciricito',
 'panama/colon/cristobal',
 'panama/colon/maria chiquita',
 'panama/colon/na',
 'panama/colon/nueva esperanza',
 'panama/colon/pilon',
 'panama/colon/sabanitas',
 'panama/colon/san juan',
 'panama/darien/meteti',
 'panama/darien/meteti',
 'panama/darien/yaviza',
 'panama/guna yala/aguadulce',
 'panama/guna yala/ailigandi',
 'panama/guna yala/baco',
 'panama/guna yala/barrios unidos',
 'panama/guna yala/bugaba',
 'panama/guna yala/carlos santana avila',
 'panama/guna yala/cirilo guaynora',
 'panama/guna yala/david',
 'panama/guna yala/el calabacito',
 'panama/guna yala/feuillet',
 'panama/guna yala/finca 30',
 'panama/guna yala/guabito',
 'panama/guna yala/nargada',
 'panama/guna yala/nargana',
 'panama/guna yala/nargana',
 'panama/guna yala/pacora',
 'panama/guna yala/pinogana',
 'panama/guna yala/pocri',
 'panama/guna yala/puerto armuelles',
 'panama/guna yala/salto dupi',
 'panama/guna yala/vista alegre',
 'panama/herrera/chitre',
 'panama/herrera/san juan bautista',
 'panama/los santos/las tablas',
 'panama/los santos/na',
 'panama/na/na',
 'panama/panama center/44189',
 'panama/panama center/amelia denis de icaza',
 'panama/panama center/ancon',
 'panama/panama center/betania',
 'panama/panama center/curundu',
 'panama/panama center/el chorrillo',
 'panama/panama center/juan diaz',
 'panama/panama center/las mananitas',
 'panama/panama center/las mananitas',
 'panama/panama center/parque lefevre',
 'panama/panama center/pedregal',
 'panama/panama center/pedregal',
 'panama/panama center/puerto caimito',
 'panama/panama center/rio abajo',
 'panama/panama center/san francisco',
 'panama/panama center/san francisco',
 'panama/panama center/santa ana',
 'panama/panama center/tocumen',
 'panama/panama center/tocumen',
 'panama/panama east/chepo',
 'panama/panama east/pacora',
 'panama/panama east/san martin',
 'panama/panama east/torti',
 'panama/panama north/caimitillo',
 'panama/panama north/caimitillo',
 'panama/panama north/chilibre',
 'panama/panama north/chilibre',
 'panama/panama north/ernesto cordoba',
 'panama/panama north/las cumbres',
 'panama/panama north/las cumbres',
 'panama/panama oeste/arraijan',
 'panama/panama oeste/barrio colon',
 'panama/panama oeste/burunga',
 'panama/panama oeste/el coco',
 'panama/panama oeste/guadalupe',
 'panama/panama oeste/juan demostenes a',
 'panama/panama oeste/juan demostenes a.',
 'panama/panama oeste/puerto caimito',
 'panama/panama oeste/santa clara',
 'panama/panama oeste/veracruz',
 'panama/panama oeste/vista alegre',
 'panama/san miguelito/amelia denis de icaza',
 'panama/san miguelito/arnulfo arias',
 'panama/san miguelito/arnulfo arias',
 'panama/san miguelito/atalaya',
 'panama/san miguelito/belisario frias',
 'panama/san miguelito/belisario frias',
 'panama/san miguelito/belisario porras',
 'panama/san miguelito/belisario porras',
 'panama/san miguelito/jose domingo espinar',
 'panama/san miguelito/jose domingo espinar',
 'panama/san miguelito/omar torrijos',
 'panama/santiago de veraguas/la colorada',
 'panama/santiago de veraguas/las palmas',
 'panama/santiago de veraguas/los algarrobos',
 'panama/santiago de veraguas/rodrigo luque',
 'panama/santiago de veraguas/san francisco',
 'panama/santiago de veraguas/san martin',
 'panama/santiago de veraguas/san martin de porres',
 'panama/santiago de veraguas/santiago',
 'panama/santiago de veraguas/sona',
 'parroquia tarqui',
 'patient acquired infection in congregation',
 'patient arrived from uae',
 'patient from china',
 'patient infected in afghanistan / kabul',
 'patient infected in community',
 'patient infected in wuhan, south china seafood market related',
 'patient probably infected in wuhan. found positive the day of return to belgium',
 'patient residence: spain / aragon / caspe',
 'patient residence: spain / aragon / fraga',
 'patient residence: spain / aragon / monzon',
 'patient residence: spain / aragon / tamarite de litera',
 'patient residence: spain / balear islands / ibiza',
 'patient residence: spain / balear islands / menorca',
 'patient residence: spain / balear islands / palma',
 'patient residence: spain / basque country / musques',
 'patient residence: spain / cantabria / laredo',
 'patient residence: spain / cantabria / pielagos',
 'patient residence: spain / cantabria / polanco',
 'patient residence: spain / cantabria / ramales de la victoria',
 'patient residence: spain / cantabria / torrelavega',
 'patient residence: spain / cantabria / zurita',
 'patient residence: spain / castilla y leon / astorga',
 'patient residence: spain / castilla y leon / benavides de orbigo',
 'patient residence: spain / castilla y leon / bercianos del paramo',
 'patient residence: spain / castilla y leon / la baneza',
 'patient residence: spain / castilla y leon / montejos del camino',
 'patient residence: spain / castilla y leon / trobajo del camino',
 'patient residence: spain / castilla y leon / val de san lorenzo',
 'patient residence: spain / castilla y leon / villaobispo de las regueras',
 'patient residence: spain / castilla y leon / villarejo de orbigo',
 'patient residence: spain / castilla y leon / villaturiel',
 'patient residence: spain / comunitat valenciana / albalat dels sorells',
 'patient residence: spain / comunitat valenciana / tavernes blanques',
 'patient residence: spain / la rioja / camprovin',
 'patient residence: spain / la rioja / leiva',
 'patient residence: spain/andalusia/alhendin',
 'patient residence: spain/asturias/bimenes',
 'patient residence: spain/asturias/gijon',
 'patient residence: spain/asturias/grado',
 'patient residence: spain/asturias/langreo',
 'patient residence: spain/asturias/laviana',
 'patient residence: spain/asturias/mieres',
 'patient residence: spain/asturias/panes',
 'patient residence: spain/asturias/pravia',
 'patient residence: spain/asturias/siero',
 'patient residence: spain/asturias/tineo',
 'patient seeking testing in a local hospital',
 'pediatric hospital asu',
 'penacova',
 'penapolis',
 'perez zeledon',
 'pococi',
 'prague and central czechia',
 'prague and central czechia',
 'praram 9',
 'qalyobeyyah',
 'qps-mra',
 'quarantine center',
 'quarantine center, ministry of health luwait',
 'quarantine center; travel history: asia / maldives',
 'quarantine station at haneda international airport. covid-19 positive case who entered from paris, france',
 'quarantine:airport quarantine station in japan',
 'queluz',
 'ramallah',
 'ramsau, salzburg',
 'reboleira',
 'recent visit to italy',
 'related to epi_isl_406596',
 'related to epi_isl_408430',
 'residence europe / belgium / limburg / lanaken',
 'residence: africa / canary islands / las palmas de gran canaria',
 'residence: africa / morocco',
 'residence: asia',
 'residence: europe / canary islands / lanzarote',
 'residence: europe / spain / andalusia / alfacar',
 'residence: europe / spain / andalusia / almeria',
 'residence: europe / spain / andalusia / antequera',

In [41]:
df[df["Additional location information"].str.lower() == 'venice, italy']

,Accession ID,Submission date,Virus name,Collection date,Host,Additional location information,Sampling strategy,Gender,Patient age,Patient status,...,AA Substitutions,age_group,clinical_status,hospitalization_status,severity,who_category,continent,country,state,city
61618,EPI_ISL_419667,2020-04-03,hCoV-19/Austria/CeMM0014/2020,2020-03-13,Human,"Venice, Italy",NaN,Female,50.0,unknown,...,"(NSP3_K19R,NSP12_P323L,Spike_D614G)",unknown,unknown,unknown,unknown,Unknown,Europe,Austria,NaN,NaN

Let's retain the following columns:
- `Accession ID`
- `Collection date`
- `Submission date`
- `Location`
- `Additional location information`
- `Gender`
- `Patient age`
- `Patient status`
- `Last vaccinated`
- `Additional host information`

In [ ]:
cols = ["Accession ID", "Collection date", "Submission date", "Location", "Gender", "Patient status", "Patient age", "Additional location information", "Last vaccinated", "Additional host information"]
df = df[cols]
df.info()

In [ ]:
df["Last vaccinated"].value_counts()

In [ ]:
df[df["Last vaccinated"] == "Suspeito de reinfecção"]

`Suspeito de reinfecção` is Portugese for Suspected Re-infection. So, it can be considered as `Patient status` rather than vaccination status.

In [ ]:
index = df[df["Last vaccinated"] == "Suspeito de reinfecção"].index
df.loc[index, "Patient status"] = "Suspected Re-infection"

Next, let's standardize vaccination status

In [ ]:
df = standardize_vaccine_status(df)
df.shape, df["Last vaccinated"].value_counts()

According to [Ramarao-Milne et. al, 2022](https://www.csbj.org/article/S2001-0370(22)00219-7/fulltext), there is only `0.3%` of meaningful patient data in current available EpiCoV database. Let's see if this applies to our sample as well.

In [ ]:
inclusion_exclusion(df)

Next, let's standardize the patient status

In [ ]:
df["Patient status"] = df["Patient status"].fillna("Unknown")
df.info()

In [ ]:
df["Clinical status"], df["Hospitalization status"], df["Severity"], df["WHO category"] = np.nan, np.nan, np.nan, np.nan
df = map_pat_status(df, df_pat, "Clinical status")
df = map_pat_status(df, df_pat, "Hospitalization status")
df = map_pat_status(df, df_pat, "Severity")
df = map_pat_status(df, df_pat, "WHO category")

In [ ]:
df.info()

## Collection Submission delay statistics

In [ ]:
df["Submission date"] = pd.to_datetime(df["Submission date"], format="mixed")
df["Collection date"] = pd.to_datetime(df["Collection date"], format="mixed")

df["Collection date"].min(), df["Collection date"].max(), df["Submission date"].min(), df["Submission date"].max()

Let us validate if `Submission_date` is after the `Collection_date`

In [ ]:
df[df["Collection date"] > df["Submission date"]].shape

Find average time between collection of sample and submission of sequence collected on or after Jan 2020

In [ ]:
print(f"Number of sequences before 2020: {len(df[df["Collection date"] < pd.to_datetime("2020-01-01")])}")
df = df[df["Collection date"] >= pd.to_datetime("2020-01-01")]
df["collection_to_submission_days"] = (df["Submission date"] - df["Collection date"]).dt.days
df["collection_to_submission_days"].describe()

In [ ]:
plt.figure(figsize=(10, 4))
sns.histplot(df["collection_to_submission_days"], bins=50, kde=True, color='blue', stat='density')
sns.lineplot(x=sorted(df["collection_to_submission_days"]), 
             y=np.full(df.shape[0], 0), color='black', linewidth=2)
mean_days = df["collection_to_submission_days"].mean()
plt.axvline(mean_days, color='red', linestyle='--', label=f"Mean = {mean_days:.2f} days")

# Place annotation above the mean line, at the top of the plot
ymax = plt.gca().get_ylim()[1]
plt.annotate(f"Mean = {mean_days:.2f}", xy=(mean_days, ymax*0.7), xytext=(mean_days+0.5, ymax*0.85),
             arrowprops=dict(facecolor='red', arrowstyle='->'), color='red', fontsize=11)

plt.xlabel("Collection to Submission Days (days)")
plt.title(f"Distribution of time between Collection and Submission Dates | {YEAR}")
plt.legend()
plt.tight_layout()
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.savefig(os.path.join(PLOTS_PATH, f"collection_to_submission_days_distribution_{YEAR}.png"), dpi=300)
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))

# Plot histograms for submission dates
sns.histplot(df["Submission date"], bins=10, color="orange", label="Submission date", kde=False, alpha=0.4)

# Calculate means
mean_submission = df["Submission date"].mean()

# Plot mean lines
plt.axvline(mean_submission, color="red", linestyle="--", label=f"Mean Submission: {mean_submission.date()}")

# Annotate the bars
ax = plt.gca()
for p in ax.patches:
    ax.annotate(str(int(p.get_height())), (p.get_x() + p.get_width() / 2, p.get_height()),
                ha='center', va='bottom', fontsize=10)

plt.xlabel("Date")
plt.ylabel("Count")
plt.title(f"Distribution of Submission Dates | {YEAR}")
plt.legend()
plt.tight_layout()
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.savefig(os.path.join(PLOTS_PATH, f"submission_dates_spread_{YEAR}.png"), dpi=300)
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))

# Plot histograms for collection dates
sns.histplot(df["Collection date"], bins=10, color="orange", label="Collection date", kde=False, alpha=0.4)

# Calculate means
mean_collection = df["Collection date"].mean()

# Plot mean lines
plt.axvline(mean_collection, color="red", linestyle="--", label=f"Mean Collection: {mean_collection.date()}")

# Annotate the bars
ax = plt.gca()
for p in ax.patches:
    ax.annotate(str(int(p.get_height())), (p.get_x() + p.get_width() / 2, p.get_height()),
                ha='center', va='bottom', fontsize=10)

plt.xlabel("Date")
plt.ylabel("Count")
plt.title(f"Distribution of Collection Dates | {YEAR}")
plt.legend()
plt.tight_layout()
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.savefig(os.path.join(PLOTS_PATH, f"collection_dates_spread_{YEAR}.png"), dpi=300)
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))

# Plot histograms for collection and submission dates
sns.histplot(df["Collection date"], bins=10, color="skyblue", label="Collection date", kde=False)
sns.histplot(df["Submission date"], bins=10, color="orange", label="Submission date", kde=False, alpha=0.2)

# Calculate means
mean_collection = df["Collection date"].mean()
mean_submission = df["Submission date"].mean()

# Plot mean lines
plt.axvline(mean_collection, color="blue", linestyle="--", label=f"Mean Collection: {mean_collection.date()}")
plt.axvline(mean_submission, color="red", linestyle="--", label=f"Mean Submission: {mean_submission.date()}")

# Annotate lead time
lead_time = (mean_submission - mean_collection).days
plt.annotate(
    f"Delay in submission: {lead_time} days",
    xy=(mean_submission, plt.ylim()[1]*0.8),
    xytext=(mean_submission, plt.ylim()[1]*0.95),
    arrowprops=dict(facecolor='green', edgecolor='green', arrowstyle='->', lw=2),
    color="black",
    fontsize=14,
    ha='left'
)

plt.xlabel("Date")
plt.ylabel("Count")
plt.title(f"Distribution of Collection and Submission Dates | {YEAR}")
plt.legend()
plt.tight_layout()
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.savefig(os.path.join(PLOTS_PATH, f"collection_submission_dates_distribution_{YEAR}.png"), dpi=300)
plt.show()

In [ ]:
df["Gender"].value_counts()

In [ ]:
df["Patient status"].value_counts()

In [ ]:
df["Patient age"].value_counts()

In [ ]:
df[~df["Gender"].isin(["Male", "Female", "unknown"])]

In [ ]:
# Swap the two values in these rows (Patient age and Patent gender)
genders = ["male", "female", "unknown"]
for i, row in df[~df["Gender"].str.lower().isin(genders)].iterrows():
    age = row["Patient age"]
    if age.lower() in genders:
        df.at[i, "Patient age"] = row["Gender"]
        df.at[i, "Gender"] = age

In [ ]:
df["Gender"].value_counts()

In [ ]:
index =